### ISSUE TITLE
Program freezes indefinitely when setting (hidden) window position [Windows]

### ISSUE THREAD

**Issue by Lisoph** [rust-windowing/glutin#1033]
With a combination of getting/setting the window position, window size and window visiblity, the application freezes indefinitely on a final `GlWindow::set_position` call.

What seems to cause the problem:
1. Set the visibility to false
2. Set the window position
3. Set the visibility to true

Reproducable on HEAD and 0.16.0. Not reproducable with winit alone.

Code to reproduce (HEAD):

```Rust
extern crate glutin;
use glutin::GlContext;

fn main() {
    let mut events_loop = glutin::EventsLoop::new();
    let window = glutin::WindowBuilder::new()
        .with_title("A fantastic window!")
        .with_always_on_top(true)
        .with_dimensions((640, 480).into())
        .with_visibility(false);
    let context = glutin::ContextBuilder::new()
        .with_vsync(true)
        .with_multisampling(4)
        .with_srgb(false);
    let window = glutin::GlWindow::new(window, context, &events_loop).unwrap();

    let center = true;

    if center {
        if let Some(size) = window.get_inner_size() {
            let dpi = window.get_hidpi_factor();
            let size = size.to_physical(dpi);
            let monitor_size = window.get_current_monitor().get_dimensions(); // physical
            let pos = glutin::dpi::PhysicalPosition::new(
                monitor_size.width / 2.0 - size.width / 2.0,
                monitor_size.height / 2.0 - size.height / 2.0,
            );
            println!("Setting window pos: {:?}", pos);
            window.set_position(pos.to_logical(dpi)); // freezes :-()
        }
    }

    window.show();

    events_loop.run_forever(|event| {
        match event {
            glutin::Event::WindowEvent { event, .. } => match event {
                glutin::WindowEvent::CloseRequested => return glutin::ControlFlow::Break,
                _ => (),
            },
            _ => ()
        }

        let _ = window.swap_buffers();
        glutin::ControlFlow::Continue
    });
}
```

**Comment by francesca64** [comment]
> `GlWindow::set_position`

That method just comes from deref'ing to `winit::Window::set_position`, so there's no difference there.

This sounds like it would be related to tomaka/winit#391, but this only happening with glutin is surprising... still, I'm not optimistic about this being fixable with our current winit backend architecture, which has *several* known deadlocks and other issues.

> `monitor_size.width / 2.0 - size.width / 2.0`

This can be simplified to `(monitor_size.width - size.width) / 2.0`.

**Comment by Lisoph** [comment]
Yeah it's weird this is only happening with glutin. I rewrote my stripped down example code to call winit directly, but then it all works just fine. I will investigate a bit more this weekend (hopefully).

Awaiting the new backend architecture is probably the best idea.

Thanks for tip!

**Comment by JohnDoneth** [comment]
As of Winit 0.16.2, setting visibility to false and setting the window position before showing the window has no effect on the window position. The window acts as if there was no call to set it's position.

**Comment by kchibisov** [comment]
there's no winit anymore in glutin.
