### ISSUE TITLE
Program not exiting when window is closed on win32

### ISSUE THREAD

**Issue by matanui159** [rust-windowing/glutin#1042]
I'm having issue with my current project, [mint2d](https://github.com/matanui159/mint2d.rs), where the programs aren't exiting after the window is closed. I first believed this was an issue with my code but the further I look into it the more I think its an issue with glutin.

However the code is a bit big and messy and I can't exactly pinpoint and reproduce the issue. Also, the code works fine on my laptop while having latest dependencies (`cargo update`) but doesn't work on my desktop which has the exact same code and latest dependencies.

Here are my findings so far. First I found the issue was with this line:
```rust
graphics.window.swap_buffers()
	.map_err(|error| WindowError::InternalError(
		ToString::to_string(&error),
		Backtrace::new()
	))?;
```
as commenting it out would fix the issue. I later found out that commenting out this line instead also fixes the issue:
```rust
let context = ContextBuilder::new()
	.with_gl(GlRequest::Specific(Api::OpenGl, (3, 2)))
	.with_vsync(config.vsync) // <-- this line
	.with_multisampling(config.msaa);
```
and if I set `config.vsync = false` it also fixes it, so clearly the issue is with vsync causing swap_buffers to act weird and never exit. However, I should point out here that the main function does finish, so it doesn't freeze. Just afterwards the program itself never ends,

However, all this said, I can't reproduce the issue. This code works fine:
```rust
extern crate glutin;
use glutin::*;

pub fn test() {
	let mut events = EventsLoop::new();
	let window = WindowBuilder::new();
	let mut context = ContextBuilder::new();
	context = context.with_vsync(true);
	let glwindow = GlWindow::new(window, context, &events).unwrap();

	unsafe {
		glwindow.make_current().unwrap();
	}

	let mut running = true;
	while running {
		events.poll_events(|event| {
			match event {
				Event::WindowEvent { event, .. } => {
					match event {
						WindowEvent::CloseRequested => running = false,
						_ => ()
					}
				},
				_ => ()
			}
		});

		glwindow.swap_buffers().unwrap();
	}
}
```

I do have a few `Rc` types scattered about my code for two of my objects, however one of them I can 100% say gets dropped, while the other being `GlWindow`. I was able to make a fake `GlWindow` wrapper so I could implement `Drop` and it seemed to be dropped, however I can only 99.9% confirm this. I will keep looking, if you have any suggestions as to what could be causing this issue or things I could try, that would be helpful as well.

**Comment by matanui159** [comment]
I was finally able to reproduce the issue, it was a combination of three things that all need to happen for this issue to occur. This code here doesn't exit properly on my desktop while exiting properly on my laptop. More testing on more windows machines may be required:

```rust
extern crate glutin;
use glutin::*;

fn main() {
	// step 1. make GlWindow outlive EventsLoop
	let glwindow;

	{
		let mut events = EventsLoop::new();
		let window = WindowBuilder::new();
		let mut context = ContextBuilder::new();

		// step 2. enable v-sync
		context = context.with_vsync(true);
		glwindow = GlWindow::new(window, context, &events).unwrap();

		unsafe {
			glwindow.make_current().unwrap();
		}

		let mut running = true;
		while running {
			events.poll_events(|event| {
				match event {
					Event::WindowEvent { event, .. } => {
						match event {
							WindowEvent::CloseRequested => running = false,
							_ => ()
						}
					},
					_ => ()
				}
			});

			// step 3. swap buffers
			glwindow.swap_buffers().unwrap();
		}
	}
}
```

For the time being I'll try refactoring my code to see if I can get `GlWindow` to get dropped first.

**Comment by francesca64** [comment]
At first glance I thought this would just be #862, but your code isn't consistent with that (plus, it's quite possible that issue is really two issues...).

**Comment by matanui159** [comment]
I believe that issue was just rendering in the event loop which slowed down the program preventing it from closing, and it seems to have been solved.

As for this issue like I said its most likely an issue with my system. However, its always bugged me how the API (or more specifically, the winit API) is designed in such a way that a `Window` can out live a `EventsLoop` without the compiler complaining.

**Comment by ZeGentzy** [comment]
And eventloop 2.0 is now a thing!
