### ISSUE TITLE
Slow incremental build time

### ISSUE THREAD

**Issue by ifschleife** [rust-windowing/glutin#1050]
Hi there.

I've created a test crate with the example code from the ReadMe. Initial build time takes a while but that's ok, of course.
But, when I add a simple keyboard input check that just changes the gl clear color, like this:
```                    
glutin::WindowEvent::KeyboardInput{ input, .. } => {
    if let Some(glutin::VirtualKeyCode::Space) = input.virtual_keycode {
        unsafe {
            gl::ClearColor(0.0, 0.0, 1.0, 1.0);
        }
    }
},
```
Then building the crate takes ~10s. This is reproducible, so removing that section takes 10s again.
This is just an example of course. Incremental build times seem to be super long.

If I do the same with `glfw-rs` incremental build time is ~2s. Am I doing something wrong? Is there an obvious way to speed things up? I'm new to rust, so is there maybe some compiler flag I should be setting? Or is this a current limitation of glutin?

Thanks.

**Comment by ZeGentzy** [comment]
@1108

**Comment by ZeGentzy** [comment]
Hey,

So while we did try to improve build speeds, when it comes to recompile times, not much we can really do, as this is more of a Rust problem. See #1108 and #1110 for what we've tried.

Anyways, you could always try enabling incremental builds.
Tested via ```rm target -rf; rm glutin*/target -rf; export CARGO_INCREMENTAL=<Either 1 or blank space>; cargo build --example window;``` followed by ```time sh -c "for i in \`seq 1 10\`; do touch {glutin_examples/,}examples/window.rs || cargo build --example window; done"```

Glutin 0.20 w/inc: 31.67s user **10.04s system** 99% cpu **42.084 total**
Glutin 0.20 wo/inc: 51.87s user 10.15s system 118% cpu 52.515 total
Glutin 0.19 w/inc: sh -c   **31.12s** user 10.55s system **98% cpu** 42.380 total
Glutin 0.19 wo/inc: 52.97s user 10.18s system 117% cpu 53.644 total

**Comment by kchibisov** [comment]
Glutin now is very fast to build.
