### ISSUE TITLE
Window example doesnt render quite right when i move it from a hidpi screen to 1x, or vice versa

### ISSUE THREAD

**Issue by agmcleod** [rust-windowing/glutin#1068]
Tested on macos high sierra, dont have a hidpi windows setup to test i'm afraid.

When I run the example, it appears on my main screen (the laptop hidpi 2), and looks like:

<img width="1025" alt="image" src="https://user-images.githubusercontent.com/113275/46050831-3baca400-c104-11e8-9d25-1eb30ee3a099.png">

When i drag it to the second monitor, which is a standard 24" 1080p. It gets zoomed in sorta.

![image](https://user-images.githubusercontent.com/113275/46050849-4c5d1a00-c104-11e8-8704-ae0806608175.png)

Once i drag the window corner to resize it, it fixes itself. I tried updating the example to handle the hidpi change, but it hasnt improved.

    match event {
        glutin::Event::WindowEvent { event, .. } => match event {
            glutin::WindowEvent::CloseRequested => running = false,
            glutin::WindowEvent::HiDpiFactorChanged(dpi_factor) => {
                let logical_size = gl_window.get_inner_size().unwrap();
                gl_window.resize(logical_size.to_physical(dpi_factor));
                println!("{:?} - {:?}", event, logical_size.to_physical(dpi_factor));
            },
            glutin::WindowEvent::Resized(logical_size) => {
                let dpi_factor = gl_window.get_hidpi_factor();
                gl_window.resize(logical_size.to_physical(dpi_factor));
                println!("{:?} - {:?}", event, logical_size.to_physical(dpi_factor));
            },
            _ => (),
        },
        _ => ()
    }

In the terminal, this is the output i see:

    HiDpiFactorChanged(2.0) - PhysicalSize { width: 2048.0, height: 1536.0 }
    Resized(LogicalSize { width: 1024.0, height: 768.0 }) - PhysicalSize { width: 2048.0, height: 1536.0 }
    HiDpiFactorChanged(1.0) - PhysicalSize { width: 1024.0, height: 768.0 }
    Resized(LogicalSize { width: 1024.0, height: 768.0 }) - PhysicalSize { width: 1024.0, height: 768.0 }

**Comment by francesca64** [comment]
IIRC the [example rendering code](https://github.com/tomaka/glutin/blob/209ab925f5325c35b8c35020e2d9a85f519f84c3/examples/support/mod.rs) doesn't handle resizes at all. The triangle verts are never transformed, so they'll be in the same place after resizing.

(`HiDpiFactorChanged` also wouldn't need to be handled separately like this, as any DPI change that results in a resize would be accompanied by `Resized`. The former event is still useful if you're explicitly/specifically interested in DPI changes, though.)

**Comment by agmcleod** [comment]
@francesca64 When i resize the screen with my above code, the scene skews with the new size. So the triangle stretches, which is what i expect.

Though im not sure why the scene is offset upon moving it to the other monitor, and how to handle that.

**Comment by kchibisov** [comment]
Fixed in #1439.
