### ISSUE TITLE
Use static generator in the android example

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/glutin#113]
See:
- https://android.googlesource.com/platform/frameworks/native/+/2dccfdcd265ca86cca5ac863d921e5c647b93073/opengl/libs/EGL/getProcAddress.cpp#74
- https://github.com/servo/gleam/blob/master/src/lib.rs#L42
- https://twitter.com/ID_AA_Carmack/status/387383037794603008

**Comment by kchibisov** [comment]
Not relevant anymore.
