### ISSUE TITLE
Add ability to choice between EGL and GLX on linux, without changing the opengl version.

### ISSUE THREAD

**Issue by goddessfreya** [rust-windowing/glutin#1140]

**Comment by sumit0190** [comment]
@ZeGentzy Are you working on this already? I started using this in a project a couple of days ago and I thought "this'd be a nice-to-have" and started hacking on it, but only later realized that this was made into an issue already.

**Comment by ZeGentzy** [comment]
If you have it already done against master, I'd be happy to merge it in for v0.22.

I'm only working on having this to have it ready for v0.23, via the upcoming `plat_attrs` for `ContextBuilder`.

**Comment by sumit0190** [comment]
Oh I'd have to clean it up by loads: what I have right now is a terrible hack I put in just to test my logic with both EGL and GLX.
I see that `PlatformAttributes` isn't in yet; maybe we should take this up AFTER you push your changes in?

**Comment by ZeGentzy** [comment]
Well yeah, cause like I said, I only intend to have it in for v0.23. If you want it in v0.22, you can backport the neccecary changes and put up a PR.

**Comment by sumit0190** [comment]
Sure thing, I'll wait; until then I'll look at other issues I can contribute to. Thanks!

**Comment by goddessfreya** [comment]
Implemented in v0.24. See #1271. Closing.
