### ISSUE TITLE
Missing tag v0.21.0

### ISSUE THREAD

**Issue by TakWolf** [rust-windowing/glutin#1150]
I found that v0.21.0 have released on  Apr 22, 2019，but there is missing tag v0.21.0 

https://github.com/rust-windowing/glutin/releases/tag/v0.21.0

For some reason, I need  to reference a clearly version code.
Could someone fix it? Thank you.

**Comment by TakWolf** [comment]
I will reference this node for the time being.

https://github.com/rust-windowing/glutin/commit/2e816ae2654ba80eb3e201d0ce51d238cc105226

**Comment by ZeGentzy** [comment]
Fixed.

**Comment by GPery** [comment]
The tag name is `c8bf494`. Shouldn't it be `v0.21.0`?
