### ISSUE TITLE
Gles2 Emscripten, missing function: emscripten_set_mousemove_callback

### ISSUE THREAD

**Issue by VZout** [rust-windowing/glutin#1151]
When I call ContextBuilder::new() I get the error `missing function: emscripten_set_mousemove_callback` when running the .html file.

Is this an issue with glutin or am I doing something wrong here?

**Comment by iceiix** [comment]
It is an issue with winit: https://github.com/rust-windowing/winit/issues/760
I have a pull request to fix the missing function error but it uncovers other (unfixed) issues: https://github.com/rust-windowing/winit/pull/767

**Comment by VZout** [comment]
Damn, so there is no way to get glutin working with emscripten at the moment?

**Comment by arcriley** [comment]
Is this error due to not having a callback set? If so, what is the correct callback?

**Comment by ZeGentzy** [comment]
This is a upstream issue, and I lack the knowledge to answer questions relating to emscripten. Please ask it upstream.

**Comment by ZeGentzy** [comment]
Closing in favor of upstream.
