### ISSUE TITLE
Change description to "OpenGL context creation library for Rust applications"

### ISSUE THREAD

**Issue by felixrabe** [rust-windowing/glutin#1153]
A description saying 

> OpenGL context creation library for Rust applications

might be more descriptive (and/or correct?) than

> Pure Rust alternative to GLFW

At least it would not require explanation of GLFW to people who don't know it.

**Comment by felixrabe** [comment]
See also https://github.com/rust-windowing/winit/wiki/Missing-features-provided-by-other-crates#winit--opengl (written by me), which already uses this proposed description. (Feel free to change the wiki page if you disagree.)

**Comment by ZeGentzy** [comment]
Such a change has been on my TODO list. File a PR and I'll accept it.

**Comment by felixrabe** [comment]
Well I can't really make a pull request for it (afaik) as I am taking about the description of the repository itself that you have to update in its settings. 🤗

**Comment by ZeGentzy** [comment]
Oh, I thought you mean't the thing in the README. Hmm, well I don't have access to the settings for this repo.

@Osspial will have to look into this.

**Comment by ZeGentzy** [comment]
Fixed!
