### ISSUE TITLE
Depth and DepthStencil buffers don't seem to be supported on iOS?

### ISSUE THREAD

**Issue by hamaluik** [rust-windowing/glutin#1160]
I'll preface this by saying I know there aren't any maintainers for iOS right now and I'll likely have to solve this on my own, but I want to keep track of this issue as I attempt to sort it out.

It seems glutin thinks that there are no supported depth (nor depth/stencil) buffer formats that are supported on iOS. I know for a fact this isn't true as I can request and use them in native objective-c or swift.

Right now I think an issue is that in the context creation code here: https://github.com/rust-windowing/glutin/blob/master/glutin/src/api/ios/mod.rs#L251-L308 glutin only generates a colour render buffer, and doesn't do anything about a depth buffer. That said, I could be mistaken as querying the pixel format after requesting a 16, 24, or 32-bit depth buffer indicates that there are 0 depth bits available, and using the following code (via glium):

```rust
for fmt in glium::texture::UncompressedFloatFormat::get_formats_list() {
    eprintln!("colour {:?} supported: {:?} renderable: {:?}", fmt, fmt.is_supported(&display), fmt.is_color_renderable(&display));
}
for fmt in glium::texture::DepthFormat::get_formats_list() {
    eprintln!("depth {:?} supported: {:?}", fmt, fmt.is_supported(&display));
}
for fmt in glium::texture::DepthStencilFormat::get_formats_list() {
    eprintln!("depthstencil {:?} supported: {:?}", fmt, fmt.is_supported(&display));
}
```

prints out:

```
colour U8 supported: true renderable: true
colour I8 supported: true renderable: false
colour U16 supported: true renderable: false
colour I16 supported: true renderable: false
colour U8U8 supported: true renderable: true
colour I8I8 supported: true renderable: false
colour U16U16 supported: true renderable: false
colour I16I16 supported: true renderable: false
colour U3U3U2 supported: true renderable: false
colour U4U4U4 supported: true renderable: false
colour U5U5U5 supported: true renderable: false
colour U8U8U8 supported: true renderable: true
colour I8I8I8 supported: true renderable: false
colour U10U10U10 supported: true renderable: false
colour U12U12U12 supported: true renderable: false
colour U16U16U16 supported: true renderable: false
colour I16I16I16 supported: true renderable: false
colour U2U2U2U2 supported: true renderable: false
colour U4U4U4U4 supported: true renderable: true
colour U5U5U5U1 supported: true renderable: true
colour U8U8U8U8 supported: true renderable: true
colour I8I8I8I8 supported: true renderable: false
colour U10U10U10U2 supported: true renderable: true
colour U12U12U12U12 supported: true renderable: false
colour U16U16U16U16 supported: true renderable: false
colour I16I16I16I16 supported: true renderable: false
colour F16 supported: true renderable: false
colour F16F16 supported: true renderable: false
colour F16F16F16 supported: true renderable: false
colour F16F16F16F16 supported: true renderable: false
colour F32 supported: true renderable: false
colour F32F32 supported: true renderable: false
colour F32F32F32 supported: true renderable: false
colour F32F32F32F32 supported: true renderable: false
colour F11F11F10 supported: true renderable: false
colour F9F9F9 supported: true renderable: false
depth I16 supported: false
depth I24 supported: false
depth I32 supported: false
depth F32 supported: false
depthstencil I24I8 supported: false
depthstencil F32I8 supported: false
```

which implies that although all the colour formats are supported and detected, none of the depth ones are somehow?

**Comment by ZeGentzy** [comment]
Take with a grain of salt but, no where in the glutin code do we set `drawableDepthFormat`.

[These docs say](https://developer.apple.com/documentation/glkit/glkview/1615583-drawabledepthformat?language=objc
) that the default value is `GLKViewDrawableDepthFormatNone`.

So, as expected, you are getting no depth buffer.

I think the iOS backend also doesn't set the following params: `drawableColorFormat` `drawableStencilFormat` `drawableMultisample`, which default to `GLKViewDrawableColorFormatRGBA8888` `GLKViewDrawableStencilFormatNone` `GLKViewDrawableMultisampleNone`, respectively.

It would be nice if someone implemented this. Should be as simple as setting those properties after calling `initWithFrame` but before making the context current.

Although, I must admit, I'm really clueless wrt ObjC, like, for example, I'm stumpted at why the docs have [two parameters](https://developer.apple.com/documentation/glkit/glkview/1615609-initwithframe?language=objc) for `initWithFrame` but we only pass one.

**Comment by hamaluik** [comment]
Glutin appears to be doing some not generally supported by GLKit. Instead of supplying a delegate class which takes care of the actual rendering while the GLKView does all the setup , Glutin subclasses GLKView directly, and then creates the framebuffer manually so I think setting `drawableDepthFormat` doesn't really do anything (I just tested this and yea, setting it doesn't seem to change anything). I'm still parsing everything but I'm not sure why Glutin subclasses GLKView instead of generated a delegate for it, as I believe this would make things both simpler and actually work?

**Comment by felixrabe** [comment]
> I'm stumpted at why the docs have [two parameters](https://developer.apple.com/documentation/glkit/glkview/1615609-initwithframe?language=objc) for `initWithFrame` but we only pass one.

https://github.com/rust-windowing/glutin/blob/2662698ab872c8c56d052fb920baa6b854328293/glutin/src/api/ios/mod.rs#L426

ObjC gets from Smalltalk the function names that are the sum of their named arguments. I don't use ObjC myself, but where in Rust you define a function like

```rust
impl Canvas { fn draw_pixel(&self, x: u32, y: u32, color: Color) {} }
```

the ObjC equivalent is a `Thing` class with a `drawPixelX:y:color:` method (or more eloquently, `drawPixelAtX:y:withColor:` or something). A method `foo:` and `foo:bar:` are two different methods.

You linked to the docs to GLKView's [`initWithFrame:context:`](https://developer.apple.com/documentation/glkit/glkview/1615609-initwithframe?language=objc) method, which takes two arguments.

If you wonder "where the heck is `initWithFrame:`", you can check whether GLKView has another method that is called `initWithFrame:`. [It does not](https://developer.apple.com/documentation/glkit/glkview?language=objc). But when you go up the class hierarchy to  [UIView](https://developer.apple.com/documentation/glkit/glkview?language=objc), then you'll find it implements [`initWithFrame:`](https://developer.apple.com/documentation/uikit/uiview/1622488-initwithframe?language=objc). That is the method that gets called here.

**Comment by ZeGentzy** [comment]
We used to subclass `UIViewController` in winit: https://github.com/rust-windowing/winit/pull/609/files#diff-6c46aa4c86605314d2bc4362928e960aL645
[
I think this was appropriate at the time, cause the docs say: ](https://developer.apple.com/documentation/uikit/uiviewcontroller)
> The UIViewController class defines the shared behavior that is common to all view controllers. You rarely create instances of the UIViewController class directly. Instead, you subclass UIViewController and add the methods and properties needed to manage the view controller's view hierarchy. 

When this code got moved to glutin, I think @mtak- just replaced it with `GLKView` [here](https://github.com/mtak-/glutin/commit/1a3066f8582ee2881890c7e7297419c8badb2fb3#diff-d6355092c6fad0d11d51fe12c02b92ebR350).

I guess this is a case of technical debt. Feel free to use `GLKViewDelegate`.

**Comment by hamaluik** [comment]
I'm looking into it but using `GLKViewDelegate` seems to imply we wouldn't have control over when rendering occurs—i.e. with canonical GLKit, I think you're only supposed to draw when your `draw` callback gets called..

**Comment by ZeGentzy** [comment]
I think it is safe to draw to the stuff from outside of the `draw` callback (although maybe not necessarily recommended).

https://developer.apple.com/documentation/glkit/glkviewdelegate/1615595-glkview
> The semantics of this method are identical to those of the draw(_:) method; [..]

https://developer.apple.com/documentation/uikit/uiview/1622529-draw
> Subclasses that use technologies such as Core Graphics and UIKit to draw their view’s content should override this method and implement their drawing code there. *You do not need to override this method if your view sets its content in other ways.* For example, you do not need to override this method if your view just displays a background color or if your view sets its content directly using the underlying layer object.

**Comment by kchibisov** [comment]
No ios support for now.
