### ISSUE TITLE
Performance issue choose_dummy_pixel_format

### ISSUE THREAD

**Issue by chichid** [rust-windowing/glutin#1166]
Trying to run the example window and headless, I noticed that choose_dummy_pixel_format is taking up to 700ms on my computer. Is that normal? 
I think most of the time in choose_dummy_pixel_format is spent in the call to ChoosePixelFormat

Operating System: Windows 10
Graphics: Nvidia GTX 970
Log:
```
$ cargo run  --example headless
   Compiling glutin v0.21.0 (C:\Users\rachidox\github\glutin\glutin)
   Compiling glutin_examples v0.1.2 (C:\Users\rachidox\github\glutin\glutin_examples)
    Finished dev [unoptimized + debuginfo] target(s) in 3.25s
     Running `target\debug\examples\headless.exe`
choose_dummy_pixel_format took 700.1076ms
Create wgl context 878.4972ms
new raw context took 878.7326ms
OpenGL version 4.6.0 NVIDIA 430.86
dbg_callback 0x8246 0x8251 0x826B "Buffer detailed info: Buffer object 1 (bound to GL_ARRAY_BUFFER_ARB, usage hint is GL_STATIC_DRAW) will use VIDEO memory as the source for buffer object operations."
dbg_callback 0x8246 0x8250 0x9147 "Pixel-path performance warning: Pixel transfer is synchronized with 3D rendering."
```

**Comment by ZeGentzy** [comment]
What happens when you compile a release build? `cargo run  --example headless --release`
Can you escape your logs next time?

I'm afraid we lack a maintainer for glutin's winit backend, so you'll have to likely work this out yourself.

**Comment by chichid** [comment]
Same problem with the release.

**Comment by ZeGentzy** [comment]
¯\\_(ツ)_/¯

**Comment by ZeGentzy** [comment]
This says 132ms https://community.amd.com/thread/158581

Also: https://www.gamedev.net/forums/topic/489100-problem-with-choosepixelformat-very-slow/

**Comment by chichid** [comment]
I just wanted to know on someone else's side how much does that function take in the context of the project. I guess this is due to the driver or something. So I'll look into it, and send a PR if I can fix it myself. If my graphics card can run far cry, it should be able to run the example fast enough! :)

**Comment by chichid** [comment]
I have an example with another library "gfx" and it seems as slow, so it has to be the opengl driver on my machine. Closing this issue for that reason.
