### ISSUE TITLE
vsync callback

### ISSUE THREAD

**Issue by SergeevPavel** [rust-windowing/glutin#1181]
Hello, I working on [library](https://github.com/JetBrains/noria-clj/tree/master) for drawing ui, and I faced with the need to get notification on display refresh. During animation I need to know when I should draw next frame. For macos I found [something](https://developer.apple.com/documentation/corevideo/1457096-cvdisplaylinksetoutputcallback?language=objc) similar to what I want. But I need to do it in a cross-platform way. Could you say is there some ability to do something like this via glutin, or not?
BTW, I read the servo code, and found that during animation they spin event loop without blocking, probably it would solve my problem, but it looks a bit wasteful.

**Comment by ZeGentzy** [comment]
winit's `RedrawRequested` event?
https://docs.rs/glutin/0.22.0-alpha1/glutin/event/enum.WindowEvent.html#variant.RedrawRequested

**Comment by SergeevPavel** [comment]
No, I expect that event should be fired after every screen refresh, like 16.7ms timer but synchronously with vsync.

**Comment by ZeGentzy** [comment]
Could you clarify what you want? I don't understand.

**Comment by SergeevPavel** [comment]
In short I want exact thing that `CVDisplayLinkSetOutputCallback` do on macos, but also on other platforms.
In details, I develop ui library, that use glutin. Regulary it workflow looks like:
* lock waiting user event
* user interaction(like mouse click)
* update state
* schedule frame preparation
* awake event loop
* draw frame
* swap buffers
But, when you decide run animation (like spinning throbber), you need to schedule new frames without whaiting user interaction, every 16.7ms and moreover synchronously with vsync. Using `CVDisplayLinkSetOutputCallback` as trigger for pushing frame looks like good idea for me, but unfortunately I can't found something similar in glutin.

**Comment by ZeGentzy** [comment]
https://docs.rs/glutin/0.22.0-alpha1/glutin/event_loop/enum.ControlFlow.html#variant.Poll + enabling vsync?

**Comment by SergeevPavel** [comment]
Thank you, it's probably best solution, especially if take into account that `CVDisplayLinkSetOutputCallback` is also [complicated topic](http://thume.ca/2017/12/09/cvdisplaylink-doesnt-link-to-your-display/).

**Comment by ZeGentzy** [comment]
Ok, geat!
