### ISSUE TITLE
Macos: build_windowed: NoAvailablePixelFormat

### ISSUE THREAD

**Issue by alexheretic** [rust-windowing/glutin#1209]
I'm testing Robo Instructus on macos with glutin `0.21`. One of the testers is getting this error running on a 2010 MacBook Pro (ie not a vm).

`build_windowed: NoAvailablePixelFormat`

I'm building the window with

```rust
// robo instructus
ContextBuilder::new()
    .with_gl_profile(GlProfile::Core)
    .with_gl(GlRequest::Specific(Api::OpenGl, (3, 3)))
    .with_depth_buffer(depth_total_bits - stencil_bits) // 24
    .with_stencil_buffer(stencil_bits) // 8
    .with_pixel_format(color_total_bits - alpha_bits, alpha_bits) // 24, 8
    .build_windowed(window_builder, &events_loop)
    .expect("build_windowed")
```

Looking at the mac platform code it looks like the error comes from
```rust
// glutin/src/platform_impl/macos/mod.rs:77
let pixel_format = IdRef::new(
    NSOpenGLPixelFormat::alloc(nil)
        .initWithAttributes_(&attributes),
);
let pixel_format = match pixel_format.non_nil() {
    None => return Err(CreationError::NoAvailablePixelFormat),
    Some(pf) => pf,
};
```

Any ideas on how I could debug this or reason why this isn't working?

Downstream with links to mac game builds: https://github.com/big-ab-games/robo-instructus/issues/229

**Comment by ZeGentzy** [comment]
I'd print out `attributes` and see what is populated with. I

'd then go commenting out lines from here 1 by one till it works: https://github.com/rust-windowing/glutin/blob/master/glutin/src/platform_impl/macos/helpers.rs#L79

I'd also find out a way to list all supported pixel formats. You can do this on linux via `glxinfo`. I've used this program on windows, and it has macos support apparently: https://apps.apple.com/app/id444052073?mt=12

**Comment by alexheretic** [comment]
It looks like this was caused by the macbook lacking hardware acceleration, which is strange as this is not a vm.

I wonder if the error messages can be improved here, ideally this would produce a `Hardware acceleration unavailable` error which would really help point in the right direction, where `NoAvailablePixelFormat` misleads.

**Comment by alexheretic** [comment]
> Should glutin print out "Hardware acceleration unavailable" or "Stencil bits unavailable"?
I guess either would be more helpful than the current situation. It's currently a wide error that can be affected by many configs and it doesn't inform you of the cause(s) at all. 

> Anyways, is it possible that the mac doesn't support hardware acceleration + some other option you are requesting? I've yet to hear of macs that don't support hardware acceleration. What's its model, os version and stuff?

As far as I can tell the model should be fine, maybe driver updates will help.

![](https://camo.githubusercontent.com/79c0b27f6b9cc88364aa32b0816dffa3624d149e/68747470733a2f2f73636f6e74656e742d6c6874362d312e78782e666263646e2e6e65742f762f74312e302d392f36393335353237365f31303231383337393739313032323031365f3733323431303938343735363431323431365f6e2e6a70673f5f6e635f6361743d313034265f6e635f6f633d41516c3067797a6e4a796e55367a34786d762d78536a49436372694b4433765445304b52756e7941395a30615773486c5f414d5351645658794e6b65724a6b686b5a55265f6e635f68743d73636f6e74656e742d6c6874362d312e7878266f683d3939663563363865383530326561383737633561633130626532666533333137266f653d3545313331463133)

**Comment by jfizz** [comment]
I believe I encountered this issue as well, described here: https://github.com/servo/pathfinder/issues/267.

The interesting part is that `rust-sdl2` seems to return a `3.3` context just fine on my machine. See `pathfinder/examples/canvas_minimal`.

**Comment by kchibisov** [comment]
Not relevant anymore.
