### ISSUE TITLE
Abaqus CAE

### ISSUE THREAD

**Issue by sharanrajindia** [rust-windowing/glutin#1218]
Dear All,
I have been using Abaqus CAE in my ubuntu 18.04 for the past year or so. It was working very well. Today when I tried to run Abaqus, I got the following error

> X Error: code 158 major 152 minor 6: GLXBadContext.
> [xcb] Unknown sequence number while processing queue
> [xcb] Most likely this is a multi-threaded client and XInitThreads has not been called
> [xcb] Aborting, sorry about that.
> ABQcaeK: ../../src/xcb_io.c:259: poll_for_event: Assertion `!xcb_xlib_threads_sequence_lost' failed.
> Abaqus Error: Abaqus/CAE Kernel exited with an error.

Any help to rectify this error is much appreciated.
Thank you.

**Comment by ZeGentzy** [comment]
Dupe: https://github.com/rust-windowing/glutin/issues/1034

We got a mesa patch here which you can use, but it breaks some part of wine: https://github.com/rust-windowing/glutin/issues/1034#issuecomment-476830226

Closing as dupe.

**Comment by ZeGentzy** [comment]
Hold on, Abaqus CAE doesn't even use glutin. Why is this being submitted here?
