### ISSUE TITLE
Screenbuffer does not resize on Mac

### ISSUE THREAD

**Issue by kanjiwar** [rust-windowing/glutin#1227]
I want to toggle the aspect ratio between 16:9 and 9:16 at runtime. Everything works fine on app start, but there is something wrong with the Mac implementation of set_inner_size(). My framebuffers resize properly but the window's screenbuffer does not change size.

@Osspial recommended calling Glutin's resize() function but this produced a black screen.

**Comment by goddessfreya** [comment]
Should probably call `glViewport` to update the viewport.

**Comment by kanjiwar** [comment]
> Should probably call `glViewport` to update the viewport.

It's not a viewport issue.

**Comment by goddessfreya** [comment]
Do you have an example I can test?

**Comment by kanjiwar** [comment]
[bug.zip](https://github.com/rust-windowing/glutin/files/4811985/bug.zip)

@goddessfreya here you go. This actually demonstrates a more general form of the bug. Simply resize the window with your mouse on mac. The red rectangle should fill the screen at all times, but it does not. It resembles a viewport issue, but I am setting the viewport properly.

**Comment by AcrylicShrimp** [comment]
I have a similar issue. When I resize the window, the screen buffer is not changing. So the rendered image is getting distorted.

**Comment by AcrylicShrimp** [comment]
> I have a similar issue. When I resize the window, the screen buffer is not changing. So the rendered image is getting distorted.

Oh, hold on, I fixed my problem. My case was that I forgot to call `ContextWrapper::resize` on resizing event handlers.
It works well after calling this function correctly.

**Comment by MarijnS95** [comment]
@AcrylicShrimp Would this also be resolved if `glutin` had a helper function to handle `winit` events? After all, `glutin` heavily builds on top of `winit`.

I'm (slowly) working on this for Android lifecycle support.

**Comment by AcrylicShrimp** [comment]
@MarijnS95 If you mean helper functions to handle window events in the `glutin`, yes, it would maybe. But I'm not sure it's a good way to go. The main problem was that it's hard to know how to resize correctly. And I didn't even know existence of the `resize` function on the `ContextWrapper`. Adding a section on the docs for resizing with detailed description would be better.

**Comment by kchibisov** [comment]
No winit in glutin anymore.
