### ISSUE TITLE
build_windowed() is very slow

### ISSUE THREAD

**Issue by ApoorvaJ** [rust-windowing/glutin#1238]
Call to `build_windowed()` takes over 550ms in a release build. The result is a noticeable white window flash before the program starts.

Minimal repro code:

```Rust
use glutin::event::{Event, WindowEvent};
use glutin::event_loop::{ControlFlow, EventLoop};
use glutin::window::WindowBuilder;
use glutin::ContextBuilder;
use std::time::SystemTime;

fn main() {
    let el = EventLoop::new();
    let wb = WindowBuilder::new();

    let time = SystemTime::now(); // <--- From here

    let _windowed_context = ContextBuilder::new().build_windowed(wb, &el).unwrap();

    println!("{:?}", SystemTime::now().duration_since(time).unwrap()); // <--- To here takes over 550ms

    el.run(move |event, _, control_flow| {
        *control_flow = ControlFlow::Wait;

        match event {
            Event::LoopDestroyed => return,
            Event::WindowEvent { ref event, .. } => match event {
                WindowEvent::CloseRequested => *control_flow = ControlFlow::Exit,
                _ => (),
            },
            _ => (),
        }
    });
}

```

glutin version: 0.22.0-alpha5
rustc version: rustc 1.39.0 (4560ea788 2019-11-04)
Windows 10 64-bit,
NVIDIA RTX 2080, Driver 436.48

I have a repro on glutin 0.21.1 as well. I do not have a repro if I only use winit.

**Comment by goddessfreya** [comment]
I'm not familiar with what tools are available on windows, but could you profile the code and provide something like a flame graph?

**Comment by ApoorvaJ** [comment]
Might take me a little time to get to it, but I will try to dig deeper.

**Comment by ApoorvaJ** [comment]
Still haven't profiled it myself, but based on this [Twitter thread](https://twitter.com/TheLazyDodo/status/1194740212179406848) and this [forum post](https://hero.handmade.network/forums/code-discussion/t/2503-%5Bday_235%5D_opengls_pixel_format_takes_a_long_time#12672), this seems to be a common problem with NVIDIA OpenGL drivers' implementation of `SetPixelFormat`/`ChoosePixelFormat`.

**Comment by ApoorvaJ** [comment]
I did a manual partial flame graph using [llogiq/flame](https://github.com/llogiq/flame), and over half of the time is indeed spent on ChoosePixelFormat. Given that this behavior is well-documented by other folks, and that the fault lies entirely in the NVIDIA OpenGL driver, I'm not going to pursue this any further.

Feel free to close this issue, or keep it around for posterity in whatever form you see fit.

![image](https://user-images.githubusercontent.com/2312221/69863979-59444300-129e-11ea-9194-1079573cb6af.png)
