### ISSUE TITLE
Decouple this from `winit`

### ISSUE THREAD

**Issue by icefoxen** [rust-windowing/glutin#1243]
Basically my dream is that `glutin` does not need to depend on a particular version of `winit`, it just does the OpenGL context setup and `winit`'s windowing and event loop and stuff is all independent of it.  `glutin` just takes a `raw-window-handle` and does its magic.

Per conversations on Discord, this is Tricky 'cause on some platforms the OpenGL context setup needs to happen at window creation time, you can't create a window and then throw an OpenGL context into it later.  So `glutin` would need to create a window and then pass its `raw-window-handle` to `winit` for it to do *its* magic.  For my purposes this seems fine, and apparently bullet point 2 in [this issue](https://github.com/rust-windowing/winit-blit/issues/1#issue-526294636) has similar problems, so this may be something we want to do anyway.

**Comment by goddessfreya** [comment]
Implemented for v0.24. See #1271. Closing.
