### ISSUE TITLE
Yank breaking versions with "*" deps

### ISSUE THREAD

**Issue by kornelski** [rust-windowing/glutin#1246]
An old version of `glutin` has dependencies specified with `"*"` version requirement (`clock_ticks = "*"`, `libc = "*"`, `compile_msg = "*"`, `user32-sys = "*"`, etc.).

Crates with such vague dependency versions became unusable, because `*` allows picking too-new semver-incompatible dependencies.
It also breaks Cargo's `minimal-versions` feature, because `*` requirement allows picking very very old dependencies that aren't compatible with Rust 1.0.

Because this old version of `glutin` is unusable and may cause problems for Cargo, I suggest yanking it:

```bash
cargo yank --vers 0.0.1
```

**Comment by goddessfreya** [comment]
cc @Osspial

**Comment by Osspial** [comment]
Huh, I'm surprised Cargo even allowed those to be uploaded.

Does this issue only happen with Glutin `0.0.1`? Glutin's got a *lot* of versions, and I don't really want to scan through all of them to find the ones with `*` dependency versions.

**Comment by kornelski** [comment]
Yes, only this one version is affected.

**Comment by Osspial** [comment]
Alright, that version has been yanked. Thank you for bringing this to our attention!
