### ISSUE TITLE
The sRGB should be disabled by default as described

### ISSUE THREAD

**Issue by katyo** [rust-windowing/glutin#1250]
As I understand the default value for srgb should be false
https://github.com/rust-windowing/glutin/blob/d6ea989dbe03ed0e8fb7836cf6575477a4ccfa46/glutin/src/lib.rs#L630-L632
but actually it is true
https://github.com/rust-windowing/glutin/blob/d6ea989dbe03ed0e8fb7836cf6575477a4ccfa46/glutin/src/lib.rs#L654-L656

**Comment by goddessfreya** [comment]
@katyo We recently changed to to true from false to resolve a common bug, but I guess we forgot to update the docs.

**Comment by goddessfreya** [comment]
Fixed: https://github.com/rust-windowing/glutin/commit/6de871ce7e8cd06cf9ed83ffa1c335402d744c28

**Comment by katyo** [comment]
Good

**Comment by LunarLambda** [comment]
docs.rs still says the default is false

https://docs.rs/glutin/0.22.0/glutin/struct.ContextBuilder.html#method.with_srgb

**Comment by atouchet** [comment]
@LunarLambda this is fixed in 0.22.1: https://docs.rs/glutin/0.22.1/glutin/struct.ContextBuilder.html#method.with_srgb
