### ISSUE TITLE
with_shared_lists is poorly named

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/glutin#1254]
The method name and documentation implies that display lists are the only objects that get shared between contexts, which very much isn't the case. You seem to be able to share [most non-container objects](https://www.khronos.org/opengl/wiki/OpenGL_Object#Object_Sharing) between contexts, so we should rename the function to reflect that and link to that wiki page.

**Comment by kchibisov** [comment]
Fixed in #1439.
