### ISSUE TITLE
Support rendering to multiple windows with a single context

### ISSUE THREAD

**Issue by Osspial** [rust-windowing/glutin#1255]
It's possible to use a single OpenGL context to render to multiple windows, on Windows and X11 at least ([see this post](https://community.khronos.org/t/multiple-opengl-windows-in-one-application/72971/3)). It would be cool if Glutin supported that usecase, although it's not entirely clear to me what the API design for that would look like. It's been on my mind on and off the past few years now though, and I figured it'd be useful to officially put down that it's a thing we could do.

**Comment by kchibisov** [comment]
Done in #1439.
