### ISSUE TITLE
[X11/EGL/Mali] EGL surface not resized on x11 window resize

### ISSUE THREAD

**Issue by ksf** [rust-windowing/glutin#1265]
Upon resizing the X11 window I get black bars around the rendered scene, the scene sometimes snapping to the lower and/or bottom window edge, sometimes staying exactly where it is. Scene renders as expected (judging by gl_FragCoord still saying that pixels are pixels, that is).

---

Some abbreviated `es2_info`:

    EGL_VERSION: 1.4 Midgard-"r14p0-01rel0"
    EGL_VENDOR: ARM
    EGL_CLIENT_APIS: OpenGL_ES
    GL_VERSION: OpenGL ES 3.2 v1.r14p0-01rel0-git(966ed26).f44c85cb3d2ceb87e8be88e7592755c3
    GL_RENDERER: Mali-T860

That's an rk3399 chip running Armbian, in particular a NanoPC-T4 and Ubuntu 18.04.3 LTS, using the media scripts to get at the binary driver blob and thus OpenGL ES via EGL under X11. (Now, the hardware can do vulkan but rockchip isn't releasing any drivers for that, that's a whole another issue).

---

I'm calling `resize` on the context as intended, however that's bound to do nothing as the call is blackholed in `platform_impl/unix/mod.rs` for X11 contexts. 

---

[Quoth Khronos on `eglSwapBuffers`](https://www.khronos.org/registry/EGL/sdk/docs/man/html/eglSwapBuffers.xhtml):

> Native Window Resizing
If the native window corresponding to surface has been resized prior to the swap, surface must be resized to match. surface will normally be resized by the EGL implementation at the time the native window is resized. If the implementation cannot do this transparently to the client, then eglSwapBuffers must detect the change and resize surface prior to copying its pixels to the native window. If surface shrinks as a result of resizing, some rendered pixels are lost. If surface grows, the newly allocated buffer contents are undefined. The resizing behavior described here only maintains consistency of EGL surfaces and native windows; clients are still responsible for detecting window size changes (using platform-specific means) and changing their viewport and scissor regions accordingly.

...which, if I'm reading that correctly, makes the behavior ARM's fault: They should be resizing the surface on their end, in `libMali.so` (where egl lives). OTOH other egl-backed apps I'm running do resize properly, which leads me to believe that context libraries that aren't glutin happen to be working around this issue.

**Comment by goddessfreya** [comment]
Can you post an example of your code.

**Comment by ksf** [comment]
`glutin_examples/examples/window.rs` shows the same behaviour, probably should have mentioned that.

**Comment by goddessfreya** [comment]
The glutin examples currently don't call `glViewport` to update the viewport, so they aren't expected to work :D

See #1251 and #1068

**Comment by goddessfreya** [comment]
To extend upon the previous comment, if `EGL_SWAP_BEHAVIOR` is ` EGL_BUFFER_DESTROYED`, then on swapping everything (as the name implies) could be destroyed by the driver. If we only update a subset of the surface cause we forgot the update the viewport, you can get black bars on the top and right, since the coords are relative to the bottom left.

**Comment by ksf** [comment]
Welp, it actually was `glViewport`. The first draw after resize still gets messed up but I'm chalking that up to X.

So I guess the examples really ought to be fixed, let's see if my fooling around produces something of suitable size (especially since the example `gl-rs` gives doesn't work with recent glutin).

**Comment by goddessfreya** [comment]
Yeah, the glutin examples should be fixed for the [next release](https://github.com/rust-windowing/glutin/pull/1239/files#diff-641abdc2d583f6df2dd9e1cbe0a4683fR66), although I do hope someone takes it on themselves to fix them for the current release.
