### ISSUE TITLE
Glutin 0.21 runs too fast? ~1000FPS. vsync issue?

### ISSUE THREAD

**Issue by paulrouget** [rust-windowing/glutin#1281]
It looks like `swap_buffer` doesn't block long enough.

Here is how I measure the FPS:

https://github.com/rust-windowing/glutin/compare/backport21...paulrouget:1000FPS

**Comment by kchibisov** [comment]
What's your platform + driver?

**Comment by paulrouget** [comment]
MacBook Pro 13. 2016. Intel Iris.

I haven't re-tested this issue recently.

**Comment by kchibisov** [comment]
Could you try master, it seems like you were trying very old glutin?
