### ISSUE TITLE
GlRequest::Specific(Api::OpenGlEs, (2, 0)) is giving the last OpenGLES available.

### ISSUE THREAD

**Issue by vinhig** [rust-windowing/glutin#1282]
**What have i done ?**
Trying to create an OpenGLES 2.0 context.
```rust
let windowed_context = ContextBuilder::new()
        .with_gl(GlRequest::Specific(Api::OpenGlEs, (2, 0)))
        .build_windowed(wb, &el)
        .unwrap();
```
Logging the gl::GetString(gl::VERSION).
```rust
let data = CStr::from_ptr(gl::GetString(gl::VERSION) as *const _)
            .to_bytes()
            .to_vec();
println!(String::from_utf8(data).unwrap());
```
**Expected Behaviour**
Having `OpenGL ES 2.0 Mesa 19.2.8` as a result.
**Actual Behaviour**
`OpenGL ES 3.0 Mesa 19.2.8` on Mesa DRI Intel(R) Sandybridge Mobile and `OpenGL ES 3.2 Mesa 19.2.8` on Mesa DRI Intel(R) UHD Graphics 620 (Kabylake GT2) .
**Hypothesis**
glutin is actually getting the last available version of OpenGLES.

**Comment by kchibisov** [comment]
I think that's how mesa works sometimes. You can be provided with higher values if you pass exact sometimes. In any way that was reworked in #1439.
