### ISSUE TITLE
failed to resolve: could not find `EventsLoop` in `glutin`

### ISSUE THREAD

**Issue by axilirate** [rust-windowing/glutin#1284]
main.rs
#[macro_use]
extern crate glium;
fn main() {
 use glium::glutin;

    let mut events_loop = glutin::EventsLoop::new();
    let wb = glutin::WindowBuilder::new();
    let cb = glutin::ContextBuilder::new();
    let display = glium::Display::new(wb, cb, &events_loop).unwrap();
}

Cargo.toml
[dependencies]
glium = "*"

**Comment by vinhig** [comment]
Examples don't use the last version of glutin.
-> check there : https://raw.githubusercontent.com/vinhig/not-a-rest-api/master/src/main.rs as an example
with glutin = "0.22.0"

**Comment by kchibisov** [comment]
if you still have issues, let us know.
