### ISSUE TITLE
Missing function: request_redraw?

### ISSUE THREAD

**Issue by daemonjax** [rust-windowing/glutin#1288]
Doesn't glutin use winit as the window backend?

If so, how can I get a working event loop without having access to the request_redraw function?

context.request_redraw() does not exist!!!

EDIT:  Ahh... it's just an IDE issue: context.window().request_redraw() works.  I found it digging through the glutin source (I was going to add it in myself).

It's just that intellij autocompletion doesn't see that window() function exists -- but the code does compile and run.  

I've been spoiled by other languages that have working IDE's. :(

Would be great if that was in the glutin examples, though.

**Comment by vinhig** [comment]
Examples don't use the last version of glutin.
-> check there : https://raw.githubusercontent.com/vinhig/not-a-rest-api/master/src/main.rs as an example
with `glutin = "0.22.0"`
