### ISSUE TITLE
Input method compatiblility

### ISSUE THREAD

**Issue by laishulu** [rust-windowing/glutin#1290]
`Alacritty` uses `glutin`.
The compatibility issue is reported there, but it should be resolved here.
https://github.com/alacritty/alacritty/issues/3562

**Comment by kchibisov** [comment]
not here, it should be in https://github.com/rust-windowing/winit

**Comment by kchibisov** [comment]
Anyway, it's already tracked there https://github.com/rust-windowing/winit/issues/1452
