### ISSUE TITLE
Crash when resizing window example on Windows 10 (STATUS_ACCESS_VIOLATION)

### ISSUE THREAD

**Issue by esrauch** [rust-windowing/glutin#1294]
Repros consistently:
> git clone https://github.com/rust-windowing/glutin
> cd glutin
> cargo run --example window

Grab a corner with the mouse and drag, quickly (between 0.5-5s) the app crashes. Tail of logged messages is always this:

MainEventsCleared
RedrawRequested(WindowId(WindowId(0x7037a)))
error: process didn't exit successfully: `target\debug\examples\window.exe` (exit code: 0xc0000005, STATUS_ACCESS_VIOLATION)

**Comment by esrauch** [comment]
It crashes on wgl SwapBuffers, I note a possibly-relevant TODO there on better error handling, but it 
 just crashes inside the SwapBuffers call without having returned a false value first:

https://github.com/rust-windowing/glutin/blob/33aec609b6da89afc3c59b8b6e294b00c52fc12b/glutin/src/api/wgl/mod.rs#L234

**Comment by dannymcgee** [comment]
If it's helpful at all, I can consistently repro this by moving the window between screens with different scale factors and then attempting to resize.

**Comment by baoziv587** [comment]
same error

**Comment by kchibisov** [comment]
Seems like a driver issue, but you can retest the latest master and open a new issue if it fails.
