### ISSUE TITLE
Calling `set_inner_size` with maximum size crashes with `STATUS_STACK_BUFFER_OVERRUN`

### ISSUE THREAD

**Issue by Boscop** [rust-windowing/glutin#1303]
If I call `set_inner_size` with the maximum (the value returned by `get_max_viewport_dimensions` which for me is `(16384, 16384)`), my process crashes with `(exit code: 0xc0000409, STATUS_STACK_BUFFER_OVERRUN)`.

Opening it in MSVC debugger says:
> Unhandled exception at 0x00007FFC35199809 (nvoglv64.dll) in prog.exe: Fatal program exit requested.

and it points to this line (maybe wrongly, because the stack is corrupted by then): https://docs.rs/glium/0.27.0/src/glium/context/mod.rs.html#735

Btw, if I call `set_inner_size` with 16K resolution `(15360, 8640)` it succeeds.

Why doesn't it work with the value returned by `get_max_viewport_dimensions`? :)

**Comment by kchibisov** [comment]
There's no such call as `get_max_viewport_dimensions` and I think it doesn't belong to glutin.
