### ISSUE TITLE
Failed to run window example on Windows 10 in VirtualBox

### ISSUE THREAD

**Issue by SergeevPavel** [rust-windowing/glutin#1308]
` cargo run --example window` leads to flashing window and:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvaila
blePixelFormat', glutin_examples\examples\window.rs:13:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: process didn't exit successfully: `target\debug\examples\window.exe` (exi
t code: 101)
```

 OpenGL Extension Viewer shows:
![image](https://user-images.githubusercontent.com/4352041/84308051-8edbba00-ab66-11ea-9ebf-b37bef901377.png)

**Comment by kchibisov** [comment]
You might have more luck with the latest master. Anyway feel free to reopen.
