### ISSUE TITLE
New Feature: Ability to "get_proc_address" with `*const c_char` directly.

### ISSUE THREAD

**Issue by Lokathor** [rust-windowing/glutin#1314]
All the actual C level functions to `get_proc_address` accept `*const c_char`, not `&str`.

In the current implementation, a user has to pass `&str`, then the library converts that to a `CString`, and then uses the pointer to that to perform the actual OS call.

Since the GL function names are stored as const values in the loader, the loader can just add the `'\0'` and then pass a `*const c_char` directly, and avoid doing an extra allocation per function load.

So a way to directly pass a `*const c_char` directly should be added. eg: `get_proc_address_raw`

**Comment by i509VCB** [comment]
#1435 has changed glutin to use `&CStr` for get_proc_address
