### ISSUE TITLE
How to manage default frame/render buffers and custom buffers on iOS

### ISSUE THREAD

**Issue by slmjkdbtl** [rust-windowing/glutin#1319]
On iOS Glutin is creating a OpenGLES frame buffer and a render buffer at `init_context`, it seems to need to be kept binded because if I bind/use my own frame buffers nothing will get drawn on screen, even if I bind it back (by modifying glutin to bind to default buffers at swap step) it doesn't work if I bind and use my own buffer every frame. I can't figure out when / which step should these default buffers should be bond and when can I use my own buffers

**Comment by slmjkdbtl** [comment]
in order to make it work now, I have to do this hack:

```rust
fn begin_frame() {
    // begin frame stuff...
    #[cfg(target_os = "ios")]
    glBindFramebuffer(FRAMEBUFFER, 1); // make sure all content I draw are actually drawn on the glutin created framebuffer, assuming its ID is 1 since it's the first created
}

fn end_frame() {
    // begin frame stuff...
    #[cfg(target_os = "ios")]
    glBindRenderbuffer(RENDERBUFFER, 1); // bind the renderbuffer created by glutin
    self.windowed_ctx.swap_buffers(); // make the EAGLContext presentRenderbuffer call
}
```

**Comment by kchibisov** [comment]
No ios support for now.
