### ISSUE TITLE
It seems swap_buffers doesn't work in expected way

### ISSUE THREAD

**Issue by kaiwk** [rust-windowing/glutin#1321]
Hello, I’m using glutin make a text input like demo. I try to redraw and invoke `swap_buffers` when event_loop poll `WindowEvent::ReceivedCharacter`, but  when i type 'ab', it only shows 'a', and keep typing, it will always lag behind one character. Why is that? I know if I put redraw logic in `Event::MainEventsCleared` it will work as i expect. 

```rust
...
match event {
    WindowEvent::ReceivedCharacter(c) => {
        // redraw
        // find window by window_id
        // window.swap_buffers()
    }
...
}

```

**Comment by kchibisov** [comment]
It depends on the platform you were using, but glutin has nothing to do with events anymore.
