### ISSUE TITLE
Getting the current context?

### ISSUE THREAD

**Issue by sztomi** [rust-windowing/glutin#1337]
I would like to integrate [iced](https://github.com/hecrj/iced) (using its glutin backend) with libmpv. Both needs an opengl context to draw, but it's iced that [creates it](https://github.com/hecrj/iced/blob/master/glutin/src/application.rs#L63)

```rust
        let context = ContextBuilder::new()
            .with_vsync(true)
            .with_multisampling(C::sample_count(&compositor_settings) as u16)
            .build_windowed(builder, &event_loop)
            .map_err(|error| {
                use glutin::CreationError;

                match error {
                    CreationError::Window(error) => {
                        Error::WindowCreationFailed(error)
                    }
                    _ => Error::GraphicsAdapterNotFound,
                }
            })?;
```

Then, this context is not exposed to the application code. Since OpenGL is stateful and there is a notion of "current context" in glutin as well, is there a way to obtain the context (and the get_proc_address pointer) from an arbitrary location in code?

**Comment by chrisduerr** [comment]
You say that you want to share the context, but then you also say iced are the ones who create it. At that point you'd want a way to use the context of iced though, right? So a way to use an existing context?

Or does iced have an API for taking an existing context instead of creating one?

**Comment by sztomi** [comment]
@chrisduerr thanks for your reply. Yeah, I want to use the context that iced created. But iced does not expose this context, so I was wondering if it's possible to obtain it via other means. iced does have an integration example: https://github.com/hecrj/iced/blob/master/examples/integration/src/main.rs#L187 so it's definitely possible to make it play nice with something else rendering in the background. But that example uses wgpu directly, not opengl (something I can't do because mpv requries opengl). 

Or would it make more sense to create a separate context for mpv and somehow blend them together (if that is possible)?

**Comment by chrisduerr** [comment]
It seems to use `iced_wgpu`, so I would expect that to do some ice specific logic. So you'd probably have to look into what `iced_wgpu` does internally to get a clue as to what is going on and how it deals with things.

Generally I don't see how exposing winit's context would help, until you find a way to plug that into where you want it used.

**Comment by sztomi** [comment]
My point mentioning that was only to demonstrate that iced is able to render on top of something else.

The problem with the linked example (and why it doesn't help me) is that it doesn't use opengl to render the background scene. iced_wgpu is a wgpu renderer (i.e. not opengl). But there _is_ an opengl renderer that uses glutin to create the context. So the reason I'm asking the above question here is that I'm hoping for an easy way to get the current context (without having to patch iced).

**Comment by chrisduerr** [comment]
Oh okay, are you saying you have glutin + iced working without any problems, but you want a way for OpenGL to expose its context so you can pass that to `libmpv`?

**Comment by sztomi** [comment]
pretty much, yes!

**Comment by chrisduerr** [comment]
Ah, that makes a lot of sense then! I suppose giving access to the context makes sense, though it would probably create some safety concerns. Unfortunately I'm not super familiar with glutin and @goddessfreya is currently taking a break, so you might have to work on this yourself if you're interested.

And I'm not sure if it is compatible with some of the planned future changes, but since there's no maintainer around to implement them it's likely not going to be a problem anyways.

**Comment by sztomi** [comment]
Thanks! I'll attempt it, but I'm not super familiar with it either.

**Comment by kchibisov** [comment]
You can get raw context from #1439. So you should be able to do that? If you need anything else open a separate issue.

**Comment by sztomi** [comment]
Thanks!
