### ISSUE TITLE
Scaled texture visible on window resize on macOS

### ISSUE THREAD

**Issue by tonsky** [rust-windowing/glutin#1340]
Hello!

If I resize a window on macOS, I can see intermediate frames that are rendered as a scaled version of the previous window size. Minimal example:

https://github.com/tonsky/glutin_resize_issue

The triangle in the top left corner is supposed to always be 800x800 px, independent of window size. In reality, on resize it briefly changes it size:

![resize](https://user-images.githubusercontent.com/285292/100883945-33eda480-34b1-11eb-9edc-f8724b9a0646.gif)

This makes pretty ugly effects for any UI with fixed-sized components (e.g. buttons, text labels) that shouldn’t scale with the window.

![resize3](https://user-images.githubusercontent.com/285292/100884238-87f88900-34b1-11eb-9d88-b87e20f60743.gif)

I suppose this has something to do with vsync or delayed events?

I also notived that some OpenGL windows (e.g. browser, electron) have different behavior: if frame does not arrive in time, they crop/letterbox opengl texture instead of resizing it. So you can see occasional black/white strips at the right/bottom edges of the window, but the content itself stays in place. Is it a thing?

**Comment by LoganDark** [comment]
I'm getting this issue too.

**Comment by kchibisov** [comment]
It might be a macOS bug tbqh. Their OpenGL is sort of broken to some extent. In general glutin doesn't depend on winit anymore, so I'm not sure that it needs action here?
