### ISSUE TITLE
build failed: digitalocean debian 10: cargo run --example window

### ISSUE THREAD

**Issue by markfirmware** [rust-windowing/glutin#1348]
cc @girba
Created debian 10 digitalocean droplet.

    sudo apt install cargo
    cargo run --example window

   Compiling smithay-client-toolkit v0.12.2
   Compiling winit v0.24.0
   Compiling glutin v0.26.0 (/home/user/github.com/rust-windowing/glutin/glutin)
error: attributes are not yet allowed on `if` expressions
   --> glutin/src/platform_impl/unix/mod.rs:105:9
    |
105 |         #[cfg(feature = "wayland")]
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `glutin`.
warning: build failed, waiting for other jobs to finish...
error: build failed

**Comment by markfirmware** [comment]
This attempt was taken directly from the readme.

**Comment by kchibisov** [comment]
Fixed in #1439.
