### ISSUE TITLE
UB in glutin

### ISSUE THREAD

**Issue by YuuriMomo** [rust-windowing/glutin#1351]
![obraz](https://user-images.githubusercontent.com/53386725/114740372-13c8ce80-9d4a-11eb-8a31-38dadcc7005b.png)
Translation: 
Exception was thrown at location 0x00007FFBAA675E16 (ntdll.dll) in veloren-voxygen.exe: 0xC0000005: Write access violation 0x0000000000000024 

address: 

glutin::windowed::ContextWrapper<glutin::context::PossiblyCurrent, winit::window::Window>::swap_buffers<winit::window::Window>(void)

Steps to reproduce on windows:
Open veloren-voxygen.exe 
Open OBS 
Create new game capture, capture specific windows and select veloren-voxygen
{repeat until crash}
close OBS  
Open OBS
}

![obraz](https://user-images.githubusercontent.com/53386725/114742190-c5b4ca80-9d4b-11eb-8975-fc37e8eedbe1.png)

**Comment by kchibisov** [comment]
That might be something in the driver you were using. Try to retest with the latest master though.

**Comment by kchibisov** [comment]
I'll close it due to rewrite in #1439.
