### ISSUE TITLE
vsync doesn't work on Linux with nvidia GPU (nvidia optimus)

### ISSUE THREAD

**Issue by jmaargh** [rust-windowing/glutin#1358]
I'm running a laptop with nvidia optimus (so intel integrated GPU by default, but can switch to the nvidia discrete GPU for either the whole system or individual applications as desired) on Linux.

glutin's vsync option works fine when running on the intel GPU, but is entirely ignored on the nvidia GPU. Minimal example:

```rust
use std::time::Instant;

fn main() {
    let event_loop = glutin::event_loop::EventLoop::new();
    let window = glutin::window::WindowBuilder::new()
        .with_title("no vsync on nvidia :(")
        .with_inner_size(glutin::dpi::LogicalSize::new(800, 600));
    let window = glutin::ContextBuilder::new()
        .with_vsync(true)
        .build_windowed(window, &event_loop)
        .unwrap();
    let window = unsafe { window.make_current().unwrap() }; 

    let mut this_frame = Instant::now();
    let mut frame_num: usize = 0;
    event_loop.run(move |event, _, control_flow| {
        *control_flow = glutin::event_loop::ControlFlow::Wait;
        match event {
            glutin::event::Event::MainEventsCleared => {
                window.window().request_redraw();
            }
            glutin::event::Event::RedrawRequested(_) => {
                let last_frame = this_frame;
                this_frame = Instant::now();
                if frame_num % 20 == 0 {
                    println!(
                        "{:4} : {:.2} Hz",
                        frame_num,
                        1.0 / this_frame.duration_since(last_frame).as_secs_f32(),
                    )
                }
                frame_num += 1;

                window.swap_buffers().unwrap();
            }
            glutin::event::Event::WindowEvent { ref event, .. } => match event {
                glutin::event::WindowEvent::Resized(size) => {
                    window.resize(*size);
                }
                glutin::event::WindowEvent::CloseRequested => {
                    *control_flow = glutin::event_loop::ControlFlow::Exit;
                }
                _ => (),
            },
            _ => (),
        }
    });
}
```

This simply logs instantaneous frame rate to stdout every 20 frames. Running on the intel GPU, I see something like this:
```
 $ DRI_PRIME=0 cargo run --bin mrp
   0 : 1552.16 Hz
  20 : 48042.28 Hz
  40 : 45814.82 Hz
  60 : 45731.01 Hz
  80 : 46572.28 Hz
 100 : 42039.77 Hz
 120 : 43890.45 Hz
 140 : 47089.85 Hz
 160 : 62.03 Hz
 180 : 59.82 Hz
 200 : 59.85 Hz
 220 : 60.22 Hz
 240 : 59.97 Hz
 260 : 60.17 Hz
 280 : 60.50 Hz
 300 : 61.78 Hz
...
```
(also not entirely sure why `RedrawRequested` initally gets called c.150 times without vsync, but that's no the main issue here)

On the nvidia GPU:
```
 $ DRI_PRIME=1 cargo run --bin mrp
   0 : 1084.55 Hz
  20 : 18073.05 Hz
  40 : 18508.24 Hz
  60 : 25125.00 Hz
  80 : 25208.60 Hz
 100 : 29380.66 Hz
 120 : 29001.48 Hz
 140 : 20047.71 Hz
 160 : 18675.18 Hz
 180 : 652.65 Hz
 200 : 17818.64 Hz
 220 : 26102.84 Hz
...
```
The behaviour is the same whether it's in "choose the GPU per-application" or "run the whole system on one GPU" mode.

This is a fairly standard Ubuntu 20.04.2 LTS install. nvidia proprietary drivers v. 460. nvidia GTX 1060 max-Q. intel i7-7700HQ. Standard Ubuntu 20.04-flavoured gnome on X11.

I'm happy to provide more details/do more testing, but I'm not sure how to debug this further right now.

**Comment by jmaargh** [comment]
Probably should have mentioned, this is with glutin 0.26.0

**Comment by maroider** [comment]
I'm hardly knowledgeable on this front, but have you checked if it works with the nouveau driver?

**Comment by jmaargh** [comment]
On further investigation, even `glxgears` doesn't respect vsync on the nvidia drivers with my machine, so this is probably not a glutin problem at all. For the benefit of anybody who might stumble across this, the current accepted wisdom seems to be this: https://askubuntu.com/a/1260966/276401 (however that doesn't seem to have fixed anything for me).

Apologies for wasting your time

**Comment by maroider** [comment]
> so this is probably not a glutin problem at all

I'll go ahead and close this issue, in that case.

> Apologies for wasting your time

I was wasting it just fine on my own :)

**Comment by maroider** [comment]
> however that doesn't seem to have fixed anything for me

Re-opened because I can't read.

**Comment by jmaargh** [comment]
I'm closing because this seems to be more likely an issue with my graphics driver. Will re-open if I can rule that out.
