### ISSUE TITLE
can/should glutin::event_loop::EventLoop be Send?

### ISSUE THREAD

**Issue by lattice0** [rust-windowing/glutin#1362]
I need to create a `glutin::event_loop::EventLoop::<GliumRendererEvent>`, but before running my event loop, I need to get an event proxy from it. The way things are wired in my code, it always end up that the event loop must be sent to another thread. However, it is not `Send`. Should I `unsafe impl Send` to it? Or is it dangerous?

**Comment by lucaszanella** [comment]
According to EventLoop docs:

> /// Note that the `EventLoop` cannot be shared across threads (due to platform-dependant logic
> /// forbidding it), as such it is neither `Send` nor `Sync`. If you need cross-thread access, the
> /// `Window` created from this `EventLoop` _can_ be sent to an other thread, and the
> /// `EventLoopProxy` allows you to wake up an `EventLoop` from another thread.

however, I need a Display from it:

```
        let wb = glutin::window::WindowBuilder::new().with_title(window_title);
        let cb = glutin::ContextBuilder::new().with_vsync(true);
        let display = glium::Display::new(wb, cb, &event_loop).unwrap();
```

and Display is not `Send`

**Comment by maroider** [comment]
I don't think that's possible, as the event loop *has* to be run on the main thread on some platforms.

As for the actual problem at hand: `glutin::ContextWrapper` is `Send`, so you can send it to another thread and initialize `glium::Display` with `Display::from_gl_window`.

**Comment by kchibisov** [comment]
You may have more luck with the new glutin api.
