### ISSUE TITLE
Crash on Raspberry Pi 3 B+

### ISSUE THREAD

**Issue by birktj** [rust-windowing/glutin#1365]
The current version of glutin seems to crash on Raspbian on the Raspberry Pi 3 B+. The error message is `CreationErrors([NoAvailablePixelFormat, OsError("Couldn't find any available vsync extension")])`. The issue can be replicated by trying to execute the `window` example on the raspberry. Older versions of glutin (eg. 0.21) does not have this problem, but I have not done a proper bisection to see where the problem appears. Not that despite the error message I have tried to explicitly disable vsync by using `with_vsync(false)`.

**Comment by kchibisov** [comment]
Fixed in #1439.
