### ISSUE TITLE
Noticeable lag on linux

### ISSUE THREAD

**Issue by BillyDM** [rust-windowing/glutin#1370]
I am using the tuix GUI library which uses glutin as a dependency. I notice that on my linux system, there is significant lag when interacting with elements when vsync is enabled. However, when i disable double buffering with `.with_double_buffer(Some(false))`, it seems to fix the issue. This might just be a problem with the amdgpu drivers, but it could be also be a problem in glutin somewhere.

The specs of my system:
- up-to-date Manjaro with the Budgie desktop environment
- linux kernel - 5.10.68-1-MANJARO
- (from the about section of the settings app) - "Graphics - Radeon RX 570 Series (POLARIS10, DRM 3.40.0, 5.10.68-1-MANJARO, LLVM 12.0.1)"

**Comment by BillyDM** [comment]
I have a hunch that some linux compositors already apply double-buffering, so this could be effectively adding a sort-of quadruple buffering.

**Comment by kchibisov** [comment]
Fixed in #1439. You can control single/double buffering now.
