### ISSUE TITLE
Windows broken on macOS if created from reattached tmux process

### ISSUE THREAD

**Issue by mijalk0** [rust-windowing/glutin#1374]
Doing the following:

1. Start tmux
2. Detach tmux
3. Close terminal
4. Open terminal
5. Attach tmux
6. Create glutin window

Seems to create an inaccessible window. A preview of the window is visible through mission control, however it is not focusable and there is no icon in the dock.

**Comment by kchibisov** [comment]
Glutin doesn't create windows anymore.
