### ISSUE TITLE
Remote desktop RDP support

### ISSUE THREAD

**Issue by JamesSmith2** [rust-windowing/glutin#1384]
Will there be a remote desktop support for it?

Tried many different parameters, but seems can't get past of that "NoAvailablePixelFormat" for RDP session. (Hypervision version).

`let event_loop = glutin::event_loop::EventLoop::new();
    let wb = glutin::window::WindowBuilder::new();
    let mut requirements = PixelFormatRequirements::default();
    requirements.alpha_bits = None;
    requirements.color_bits = None;
    requirements.depth_bits = None;
    requirements.double_buffer = None;
    requirements.hardware_accelerated = Some(true);
    requirements.srgb = true;
    requirements.stereoscopy = false;
    requirements.stencil_bits = None;

    let mut cb = glutin::ContextBuilder::new();
    cb.pf_reqs = requirements;
    let display = glium::Display::new(wb, cb, &event_loop).unwrap(); `
    
    `thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: GlutinCreationError(NoAvailablePixelFormat)', src\main.rs:21:60`

**Comment by kchibisov** [comment]
I'm not sure those have any OpenGL support. But you retry with the latest master.
