### ISSUE TITLE
Title not visible running example on Gnome 41/42/Wayland

### ISSUE THREAD

**Issue by satmandu** [rust-windowing/glutin#1391]
This is what I see running `cargo run --example window` from glutin's head on Ubuntu 22.04 (Mutter ~ 42/Wayland).

![screenshot-crop](https://user-images.githubusercontent.com/1096701/156465190-f9ecc1f7-c39c-448e-8e2f-df266bc32716.png)

As per 
https://github.com/rust-windowing/glutin/blob/b9081d2b27af0cdd15895775fe6688847a041229/glutin_examples/examples/window.rs#L10
it would seem that there should be a title, but instead, it is washed out on a white title bar.

Is there a way to get the title to show up?

I think this is referenced in both https://github.com/alacritty/alacritty/issues/4739 and https://github.com/rust-windowing/winit/issues/1312 .  Is this a Gnome issue? Do I need to open an issue on the mutter gitlab issues board?

Here is the tail of ` WAYLAND_DEBUG=1 cargo run --example window &>  wayland_title_debug.txt`
[wayland_title_debug.txt](https://github.com/rust-windowing/glutin/files/8173630/wayland_title_debug.txt)

**Comment by maroider** [comment]
It is indeed a Gnome issue. Gnome doesn't support server-side decorations, and sctk (and by extension winit) has dropped support for text in the fallback client-side decorations.

See Smithay/client-toolkit#196 for one proposed solution

**Comment by satmandu** [comment]
Thanks for that info. looks like https://github.com/cmeissl/libdecor-rs is able to do the titling! Any chance of getting that functionality here?

![screenshot-libdecor-rs-crop](https://user-images.githubusercontent.com/1096701/156581855-7fb9e5c7-1443-46c4-93ae-611ce541c048.png)

**Comment by satmandu** [comment]
Ah, I just saw https://github.com/rust-windowing/winit/issues/1967#issuecomment-1030683846 ...

**Comment by Eoin-McMahon** [comment]
What is the status on this? the problem occurs in Ubuntu 22.04 LTS

**Comment by maroider** [comment]
As I understand it, progress has stalled because integrating libdecor upstream is proving difficult. I don't recall where I read this, however.

**Comment by kchibisov** [comment]
Winit bug wrt title got fixed.
