### ISSUE TITLE
panic in egl when creating example window

### ISSUE THREAD

**Issue by tarantoa** [rust-windowing/glutin#1399]
I tried to create the example window after cloning the repo by running `cargo run --example window`, but failed with the following panic:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /mnt/d/dev/git/glium-projects/glutin/glutin/src/api/egl/mod.rs:424:32
```

With the full output at: https://pastebin.com/keEwXBtr

Panic persisted when rust nightly 1.62.0-nightly, and rust stable 1.60.0.
Running in Ubunbtu on WSL for Windows 11.

**Comment by kchibisov** [comment]
>I assumed this was a missing library since that's usually the problem on Nix, but if Ubuntu has the same issue that might not be the case.

It's not ubuntu, it was ubuntu in wsl on windows, so it's complitelly different thing.

@theduke in your case look at what alacritty requires to run in nix package and `rpath` thingy they do.

**Comment by thombruce** [comment]
As a workaround, you should be able to run the application from WSL as a Windows executable instead. This worked for me, getting started on another project:

```shell
# One time setup
sudo apt update && sudo apt install mingw-w64
rustup target add x86_64-pc-windows-gnu

# Run the application
cargo run --target x86_64-pc-windows-gnu
```

You may need to tweak this for your particular machine. To obtain a list of available targets:

```shell
rustc --print target-list
```

**Comment by kchibisov** [comment]
Fixed in https://github.com/rust-windowing/glutin/pull/1439. If not reopen with a new information.
