### ISSUE TITLE
[Bug] Getting opengl function address panics if the address contains a null terminator

### ISSUE THREAD

**Issue by morr0ne** [rust-windowing/glutin#1400]
[Window.get_proc_address](https://docs.rs/glutin/latest/glutin/struct.ContextWrapper.html#method.get_proc_address) accepts a &str which gets then converted to a CString without checking for null bytes and just calling unwrap. Passing a &str with internal null bytes will crash the program. The conversion can also be expensive considering that most opengl loaders will use a CString/CStr directly. This means that in most cases the following conversion happens:
CString => &str => CString.

it's probably a good idea for get_proc_address to ask directly for a &CStr and let the library user handle the conversion if necessary.

related #1314

**Comment by kchibisov** [comment]
That makes sense, could probably change that.

**Comment by morr0ne** [comment]
Upon further inspection it looks like some tools like the one used in the examples ([gl_generator](https://docs.rs/gl_generator/)) use &str for loading, hence probably why that was used. Making a change like that probably also means changing the generator used. [Phosporus](https://docs.rs/phosphorus/) seems to be the best alternative, it used by [glow](https://docs.rs/glow/) and transitively by bigger projects like wgpu and bevy.

**Comment by kchibisov** [comment]
Fixed in https://github.com/rust-windowing/glutin/pull/1439.
