### ISSUE TITLE
BUFFER_AGE_EXT not found in module ffi::egl

### ISSUE THREAD

**Issue by Nazariglez** [rust-windowing/glutin#1436]
Hey everybody, 

I am having an issue with the latest version of `glutin`:
``` 
   Compiling glutin v0.29.0
error[E0425]: cannot find value `BUFFER_AGE_EXT` in module `ffi::egl`
   --> /home/naz/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.29.0/src/api/egl/mod.rs:584:27
    |
584 |                 ffi::egl::BUFFER_AGE_EXT as i32,
    |                           ^^^^^^^^^^^^^^ not found in `ffi::egl`

error[E0425]: cannot find value `BACK_BUFFER_AGE_EXT` in module `ffi::glx_extra`
   --> /home/naz/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.29.0/src/api/glx/mod.rs:195:33
    |
195 |                 ffi::glx_extra::BACK_BUFFER_AGE_EXT as i32,
    |                                 ^^^^^^^^^^^^^^^^^^^ not found in `ffi::glx_extra`

For more information about this error, try `rustc --explain E0425`.
error: could not compile `glutin` due to 2 previous errors
``` 

Does anybody if this is something that related to my SO or if it's an bug on glutin? 

Thanks

--
Edit: 
* Archlinux
* Nvidia Graphic Card (privative drivers)

**Comment by kchibisov** [comment]
Are you building from source or from crates.io? Might need to run `cargo update` for glutin related crates.

**Comment by Nazariglez** [comment]
It was from crates.io. `cargo update` did the trick, thanks!

**Comment by paulotten** [comment]
I'm seeing the same thing trying to update `eframe` to `glutin = { version = "0.29.0" }`. https://github.com/emilk/egui/issues/1896#issuecomment-1209992898

I believe `glutin_egl_sys = { version = "0.1.5", path = "../glutin_egl_sys" }` in https://github.com/rust-windowing/glutin/blob/master/glutin/Cargo.toml should be updated to `0.1.6`.

**Comment by kchibisov** [comment]
The new glutin version got released fixing this.
