### ISSUE TITLE
Sharing example does not seem to work under wayland

### ISSUE THREAD

**Issue by T0b1-iOS** [rust-windowing/glutin#1447]
When running the sharing example it panics on line 28 with a 'NoAvailablePixelFormat' error when running under wayland (tested on GNOME).
Running it under X11 seems to work fine.

Output:
> thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: NoAvailablePixelFormat', glutin_examples/examples/sharing.rs:28:76

I tested on multiple computers but it would be nice to see if this is an issue with some of my configs or if this can be reproduced.

**Comment by kchibisov** [comment]
I have no plans on fixing this for the current version, but if you feel like trying #1435 it should support sharing.

**Comment by T0b1-iOS** [comment]
yup, tried a ported version of the sharing example and it seems to work with that. Thanks.

**Comment by kchibisov** [comment]
@T0b1-iOS if you can provide simple example for sharing that we can use it'll be very welcome!

**Comment by T0b1-iOS** [comment]
Sure: https://github.com/T0b1-iOS/glutin2-sharing
only works on x11/wayland right now i think. don't have a windows machine rn to test but would probably need to add an init try for wgl if the target os is windows. (i'd rather it would not conditionally compile the enum members for the display api preference).

It's basically the old sharing example since i do not have a very good understanding of opengl but it works.

**Comment by kchibisov** [comment]
I'd think how to pick the display. Note that you can use `GlxThenEgl` variants to avoid multiple `Display::from_raw`. I'll try to adapt it once I'm done with WGL stuff. It doesn't support sharing right now iirc.
