### ISSUE TITLE
How do i use mutisampiling on glutin >= 0.30?

### ISSUE THREAD

**Issue by ar37-rs** [rust-windowing/glutin#1462]

**Comment by kchibisov** [comment]
You pass this to the config

https://github.com/rust-windowing/glutin/blob/5c121bc43bb57c5af6523aa5b44bbdb42921a8b0/glutin/src/config.rs#L125

And latter you can check how many of them you have by calling https://github.com/rust-windowing/glutin/blob/5c121bc43bb57c5af6523aa5b44bbdb42921a8b0/glutin/src/config.rs#L44

**Comment by ar37-rs** [comment]
@kchibisov I  tired `cargo run --example window `and set `with_sample_buffers(8)` it gives me error like so:
```shell
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { raw_code: None, raw_os_message: None, kind: BadConfig }', glutin_examples/examples/window.rs:37:61
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
GL Version: OpenGL 4.1

**Comment by kchibisov** [comment]
It could mean that you don't have that many sample buffers. Try something lower, since it's a count of buffers. Usually `1`, `2`, and `4`. You got a note that you've passed a config that doesn't make much sense on that platform.

**Comment by kchibisov** [comment]
I think I've got your issue. I'll take a look. You want 8 samples for a buffer in a sample buffer and not sample buffers amount.

**Comment by ar37-rs** [comment]
@kchibisov, exactly. I meant anti-aliasing

**Comment by ar37-rs** [comment]
If there's a doc or quote for that (how to set anti-aliasing) on the exmaple, that would be nice.

**Comment by ar37-rs** [comment]
@kchibisov On glutin 0.29.1 there's a simple way how to do that:
```rust
#[inline]
    pub fn with_multisampling(mut self, samples: u16) -> Self {
        self.pf_reqs.multisampling = match samples {
            0 => None,
            _ => {
                assert!(samples.is_power_of_two());
                Some(samples)
            }
        };
        self
    }
```

**Comment by kchibisov** [comment]
Could you take a look at #1463? I think it should work.
