### ISSUE TITLE
0.30 beta2, Linux, thread 'main' panicked at  gl_window.surface.swap_buffers(&gl_context).unwrap(); 

### ISSUE THREAD

**Issue by golanguage** [rust-windowing/glutin#1469]
Remote connect to a Ubuntu 22.04 run on window server VM, 4G memory.

 RUST_BACKTRACE=1 **cargo run --example window**
    Finished dev [unoptimized + debuginfo] target(s) in 0.06s
     Running `/home/lion/opensrc/glutin/target/debug/examples/window`
Picked a config with 0 samples
Running on llvmpipe (LLVM 13.0.1, 256 bits)
OpenGL Version 4.5 (Core Profile) Mesa 22.0.5
Shaders version on 4.50
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error { raw_code: Some(8), raw_os_message: Some("BadMatch (invalid parameter attributes)"), kind: BadMatch }', glutin_examples/examples/window.rs:126:61
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::result::unwrap_failed
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1805:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/result.rs:1098:23
   4: window::main::{{closure}}
             at ./examples/window.rs:126:17
   5: winit::platform_impl::platform::sticky_exit_callback
             at /home/lion/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/winit-0.27.2/src/platform_impl/linux/mod.rs:849:9
   6: winit::platform_impl::platform::x11::EventLoop<T>::run_return::single_iteration
             at /home/lion/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/winit-0.27.2/src/platform_impl/linux/x11/mod.rs:390:17
   7: winit::platform_impl::platform::x11::EventLoop<T>::run_return
             at /home/lion/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/winit-0.27.2/src/platform_impl/linux/x11/mod.rs:448:31
   8: winit::platform_impl::platform::x11::EventLoop<T>::run
             at /home/lion/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/winit-0.27.2/src/platform_impl/linux/x11/mod.rs:503:25
   9: winit::platform_impl::platform::EventLoop<T>::run
             at /home/lion/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/winit-0.27.2/src/platform_impl/linux/mod.rs:755:56
  10: winit::event_loop::EventLoop<T>::run
             at /home/lion/.cargo/registry/src/mirrors.sjtug.sjtu.edu.cn-4f7dbcce21e258a2/winit-0.27.2/src/event_loop.rs:278:9
  11: window::main
             at ./examples/window.rs:99:5
  12: core::ops::function::FnOnce::call_once
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:248:5

**eglinfo  & glxinfo** see attached file

[opengl_info.txt](https://github.com/rust-windowing/glutin/files/9612008/opengl_info.txt)

**Comment by kchibisov** [comment]
If your error is consistent I'd suggest to check https://github.com/rust-windowing/glutin/blob/b92fb634f24733d4d7b353934276ad5200e0f176/glutin/src/api/glx/surface.rs#L222 before calling `swap_buffers` as well. The error may bubble up from some other place?

**Comment by ar37-rs** [comment]
Hi @kchibisov will be fixed by #1475

**Comment by golanguage** [comment]
the example is OK now
