### ISSUE TITLE
```glutin::windowed::ContextBuilder::build_windowed()``` causes NoAvailablePixelFormat error

### ISSUE THREAD

**Issue by sindre0830** [rust-windowing/glutin#1470]
Glutin version: 0.29.1
Mesa version: 22.1.7
OS: Fedora 36

After updating my OS from Fedora 34 -> Fedora 36, my rust program returns NoAvailablePixelFormat error. My laptop, which is on Fedora 35, can run the program fine on Mesa version 21.3.9. I believe the culprit is the new version of Mesa but I wanted to ask if this is a known issue or whether anyone has a fix.

**Comment by kchibisov** [comment]
The support is no longer provided for the version 0.29.1. Use latest beta releases or git master instead.
