### ISSUE TITLE
Rename `Display::from_raw` to `Display::new`

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/glutin#1478]
From reading the function name, `from_raw` heavily implies the display is created from a platform pointer for example to take ownership of an existing display or be a guest on said display.

**Comment by kchibisov** [comment]
Well, they sort of created from the raw pointer given that we pass the `RawDisplayHandle`? I think some version of that had `Display::from_native` or something like that.

But yeah, given that we want to have a `from_raw` on at least `EGL` that would be more natural for others that we provide `from_raw` for that?
