### ISSUE TITLE
Cannot build glutin

### ISSUE THREAD

**Issue by paspielka** [rust-windowing/glutin#1488]
error[E0308]: mismatched types
   --> /Users/paspielka/.cargo/registry/src/github.com-1ecc6299db9ec823/glutin-0.30.0-beta.2/src/api/cgl/config.rs:212:25
    |
212 |             is_equal != 0
    |                         ^ expected `bool`, found integer

For more information about this error, try `rustc --explain E0308`.
error: could not compile `glutin` due to previous error

running the newest version of glutin

**Comment by kchibisov** [comment]
That's fixed on master.
