### ISSUE TITLE
Also support `EGL_EXT_swap_buffers_with_damage`

### ISSUE THREAD

**Issue by i509VCB** [rust-windowing/glutin#1497]
Even though there is the `EGL_KHR_swap_buffers_with_damage` extension which glutin does support. It would probably be worth also supporting `EGL_EXT_swap_buffers_with_damage` for older drivers.

If both extensions are available, then glutin should prefer the KHR extension, `EGL_KHR_swap_buffers_with_damage`.

**Comment by kchibisov** [comment]
This is not about the drivers, but more about the platform inside mesa, since it's an extension akin to buffer age one.

It doesn't stop us from doing a fallback though.

**Comment by kchibisov** [comment]
We actually already do that.
