### ISSUE TITLE
Any chance to release quick fix for bug in swap buffers?

### ISSUE THREAD

**Issue by jakudlaty** [rust-windowing/glutin#1518]
Hi
I have launched window example on my Pc (ryzen5950x, win10 + nvidia 3090). 
```cargo run --example window --release```

Because of a bug in version 0.30.0 I can see hudge performance drop on my machine ( after 30s run every ```swap_buffers``` takes about 20ms).

Commit https://github.com/rust-windowing/glutin/commit/2a2a97209c49929027beced68e1989b8486bdec9 fixes the problem and  it's already in **master** branch

I can surely confirm that there is guge performance difference:
- **master** version:  ~4100 FPS  (example with disabled vsync)
- **v0.30.0**: ~50fps (the same example with disabled vsync)

It would be really nice from You to publish v0.30.1 because v0.30.0 can be a showstopper for windows users.

Thank You

**Comment by kchibisov** [comment]
I'm planing to make a release during weekends with some extra fixes and also publish `glutin-winit` integration.

**Comment by kchibisov** [comment]
Glutin 0.30.1 is out.
