### ISSUE TITLE
Example not transparent anymore

### ISSUE THREAD

**Issue by eEQK** [rust-windowing/glutin#1541]
I'm running the window example with `cargo clean && cargo run --example window` 

The resulting window should be transparent, but is not

bisect says the change was introduced in 821217614713d51fe204d04b17744ced0402991f (in other words previous commit did support transparency and to me it looks like the window not being transparent isn't an intended behavior)

![image](https://user-images.githubusercontent.com/15970653/208295629-67ed5229-521a-4970-825e-8dfede9b7421.png)

Only change I've added:

```diff
diff --git a/glutin_examples/src/lib.rs b/glutin_examples/src/lib.rs
index b3e2581..0c68b66 100644
--- a/glutin_examples/src/lib.rs
+++ b/glutin_examples/src/lib.rs
@@ -283,7 +283,7 @@ impl Renderer {
             self.gl.BindVertexArray(self.vao);
             self.gl.BindBuffer(gl::ARRAY_BUFFER, self.vbo);

-            self.gl.ClearColor(0.1, 0.1, 0.1, 0.9);
+            self.gl.ClearColor(0.1, 0.1, 0.1, 0.2);
             self.gl.Clear(gl::COLOR_BUFFER_BIT);
             self.gl.DrawArrays(gl::TRIANGLES, 0, 3);
```

Log with versions:
```
Running on Apple M1 Max
OpenGL Version 4.1 Metal - 76.3
Shaders version on 4.10
```
my device: macOS 12.3.1, MBP 2021 14'

**Comment by kchibisov** [comment]
Are you using native OpenGL impl? It's kind of strange that you have metal logged here as well.

Though, I'd guess some config option is missing now. So it's working, but likely not enabled... Should be trivial to fix in the example code.

**Comment by eEQK** [comment]
I've raised a PR with the fix

I thought the problem was more complicated, turns out I just looked in the wrong place 🤦
