### ISSUE TITLE
How to tell if the gl-context is hardware accelerated in `0.30`

### ISSUE THREAD

**Issue by alexheretic** [rust-windowing/glutin#1547]
Previously I could query this with `window_ctx.get_pixel_format().hardware_accelerated`. Is there a way to tell this using `0.30`?

Use case: Robo Instructus uses this to automatically set various graphics options to low.

**Comment by kchibisov** [comment]
I'm not sure how I've missed that issue, but not I don't think there's a way.

I could add something like that sure.

**Comment by kchibisov** [comment]
For now you can assume that if you've asked for hardware accelerated config you've got it.

**Comment by alexheretic** [comment]
That makes sense though isn't quite as useful. I'd like to keep working in both cases, but dial down the settings if in software mode.

I guess i could try requesting hardware then retry without and record that, but that's much less ergonomic than being able to query afterwards.

**Comment by kchibisov** [comment]
https://github.com/rust-windowing/glutin/pull/1556. Note, that llvmpipe is somehow reported as hardware accelerated as well. Though on other systems it may be more reliable here.

**Comment by alexheretic** [comment]
> #1556. Note, that llvmpipe is somehow reported as hardware accelerated as well. Though on other systems it may be more reliable here.

Thanks! Yes I believe this is the same as previous glutin versions, as my code was already manually checking for llvmpipe.
