### ISSUE TITLE
Document Wayland specifics on `make_current` and so on

### ISSUE THREAD

**Issue by kchibisov** [rust-windowing/glutin#1589]
Wayland with EGL have a notion of latching context, if you're not familiar with it, it
means that your resize, will apply only from the next frame. This is not intuitive
for anyone, and it could take folks time to understand what is going wrong with the
staff they are doing.

Such behavior should be explicitly documented. For details see the `EGL_KHR_platform_wayland`
on the khronos github page.

**Comment by i509VCB** [comment]
The platform dependent behavior should probably be documented for each platform (such as macOS where a layer or view may be set).

**Comment by kchibisov** [comment]
We have a platform sections(as well as API) on each API when needed.

**Comment by i509VCB** [comment]
Should we mention that on Wayland the surface may have a buffer attached and committed?

**Comment by kchibisov** [comment]
Could you elaborate? I know that mesa doesn't like when you attach opaque buffers behind the scenes.
