### ISSUE TITLE
badmatch on create_window_surface

### ISSUE THREAD

**Issue by uglyoldbob** [rust-windowing/glutin#1634]
I am getting a badmatch error in my egui-multiwin library (https://github.com/uglyoldbob/egui-multiwin). 
The egui-multiwin demo binary crashes when creating a transparent window on ubuntu linux.
Crash occurs at glutin::display::Display::create_window_surface.
`cargo run --bin multiwin-demo`

**Comment by kchibisov** [comment]
you're not using glutin's visual from the config to build a winit window, thus the window you can't create a window surface because your window and config has different visual leading to `BadMatch`.
