### ISSUE TITLE
Unable to create debug context with EGL when `KHR_create_context_no_error` is supported

### ISSUE THREAD

**Issue by bgK** [rust-windowing/glutin#1635]
When creating a context with EGL and the following code:
```rust
let context_attributes = ContextAttributesBuilder::new()
    .with_debug(true)
    .build(Some(window.raw_window_handle()));
```

The debug bit does not get set on the GL context:
```rust
let mut context_flags = 0;
gl.GetIntegerv(Gl::CONTEXT_FLAGS, &mut context_flags);
assert!(context_flags & Gl::CONTEXT_FLAG_DEBUG_BIT != 0);
```

This seems to be caused by this check:
https://github.com/rust-windowing/glutin/blob/e75330f5db4e73a4478f9bb9a80f7377ac44c67d/glutin/src/api/egl/context.rs#L108

[The spec for `KHR_create_context_no_error`](https://registry.khronos.org/EGL/extensions/KHR/EGL_KHR_create_context_no_error.txt) mentions an interaction with debug contexts:
> BAD_MATCH is generated if the EGL_CONTEXT_OPENGL_NO_ERROR_KHR is TRUE at
> the same time as a debug or robustness context is specified.

It's illegal to request a context that is both "no errors" and "debug", however it's fine to have a "debug" context when "no errors" is supported but not enabled.

**Comment by kchibisov** [comment]
https://github.com/rust-windowing/glutin/pull/1636

**Comment by bgK** [comment]
Thanks! I confirm the issue is fixed with your branch with EGL.
