### ISSUE TITLE
Support raw_window_handle version 0.6

### ISSUE THREAD

**Issue by collosi** [rust-windowing/glutin#1663]
The glutin crate is currently dependent on a (slightly) out-of-date version of raw_window_handle, 0.5.2.  It would be nice to have this bumped to 0.6, as I am trying to create a child window with winit's [WindowBuilder::with_parent_window()](https://docs.rs/winit/latest/winit/window/struct.WindowBuilder.html#method.with_parent_window).  That method is only available if winit is built against raw_window_handle 0.6.

**Comment by kchibisov** [comment]
you can build 0.6 handle from the 0.5 handle, it's not an issue.

**Comment by kchibisov** [comment]
There's https://github.com/rust-windowing/glutin/pull/1582

**Comment by collosi** [comment]
Yes, #1582 does include a bump to 0.6, so that's exactly what I need.  Looks like it's just waiting for a review?

**Comment by kchibisov** [comment]
yeah, pretty much. But you don't actually need 0.6 support in glutin for what you want, you can just build 0.6 from 0.5.

**Comment by kchibisov** [comment]
Ah, you can enable both 0.5 and 0.6 on winit iirc, and then just export 0.5 to get 0.5 for glutin, and 0.6 for parent window stuff.

**Comment by kchibisov** [comment]
This is fixed, though the safe methods are not here yet.
