### ISSUE TITLE
Support `winit` v0.30

### ISSUE THREAD

**Issue by marc2332** [rust-windowing/glutin#1674]
hey!

Winit recently [released](https://github.com/rust-windowing/winit/releases/tag/v0.30.0) their 0.30 version. I thought it would be a good idea to open this issue to create awareness since `glutin_window` depends on winit `0.29` 😄

Just this :)

**Comment by kchibisov** [comment]
Ah, yeah, I forgot about this crate. Updating should be trivial, more or less.

**Comment by marc2332** [comment]
> Updating should be trivial,

😭 That's what I thought... Until I saw they released the new trait-based event loop :trollface:

**Comment by codewiz** [comment]
Thank you very much. Is anyone working on the corresponding changes in glium?
