### ISSUE TITLE
Expose non-moving `PossiblyCurrentContext::make_not_current`

### ISSUE THREAD

**Issue by mickvangelderen** [rust-windowing/glutin#1704]
I want to make the context "not current" but I do not need to send the context to another thread. Can we have a non-moving variant of `PossiblyCurrentContext::make_not_current` + `NotCurrentContext::treat_as_possibly_current` that can be called on a reference?

I believe none of the context implementations need the context by-value, it's just the type-level change from `PossiblyCurrentContext` to `NotCurrentContext` that does. It seems like there could exist a method `PossiblyCurrentContext::make_not_current_in_place(&self) -> Result<()>`.

I understand that there are work-arounds for this. The easy way around this is to stuff the context into an `Option`. A probably unsound workaround is:

```rust
unsafe {
    let context = std::ptr::read(std::ptr::from_ref(&self.context));
    let Ok(context) = context.make_not_current() else {
        eprintln!("failed to make context not current");
        std::process::abort();
    };
    std::mem::forget(std::mem::replace(
        &mut self.context,
        context.treat_as_possibly_current(),
    ))
}
```

My motivation is as follows. I built an abstraction over winit and glutin that makes it a bit easier to create throw-away demos. The application lifecycle is abstracted as illustrated below:

![image](https://github.com/user-attachments/assets/06d57bf9-5e1b-4a8e-8da3-e6b40195f8be)

Because the resumed and suspended states have their own types, I can use `PossiblyCurrentContext` in the resumed state type and `NotCurrentContext` in the suspended state type. 

However, the application lifecycle is generic over the rendering back-end (OpenGL, Vulkan, ...) and the back-end stores the context. This means that I am forcing the creation of two separate state types for the rendering-back end implementation, just because `PossiblyCurrentContext::make_not_current_in_place(&self)` is not available.

I understand that there is a cost to expanding the API surface of glutin, and that this change would restrict future backends by enforcing that the un-currenting of contexts can no longer take the context by value. However, it does seem like the combination of "un-current" and "treat as possibly current" is fairly common.

**Comment by kchibisov** [comment]
>I want to make the context "not current" but I do not need to send the context to another thread. Can we have a non-moving variant of PossiblyCurrentContext::make_not_current + NotCurrentContext::treat_as_possibly_current that can be called on a reference?

Sure.

**Comment by mickvangelderen** [comment]
@kchibisov would you like me to draft a PR for this? Any ideas on the name?

**Comment by kchibisov** [comment]
The PR is relatively simple and you can default implement it on a trait with the said 2 methods.

Maybe `make_not_current_as_possibly_current`? I honestly don't have a better name suggestion for this and it's a bit clear that it's just a combinations of two functions.

**Comment by kchibisov** [comment]
Though, `make_not_current_in_place` is fine as well.

**Comment by mickvangelderen** [comment]
I think we need a constructor method in `NotCurrentGlContext` if we want to default-implement `make_not_current` because the `NotCurrentContext` type depends on the backend. Alternatively we could use a generic marker type like `Context<PossiblyCurrent>` and `Context<NotCurrent>` but that would be backwards incompatible.

**Comment by mickvangelderen** [comment]
@kchibisov thanks for the guidance!
