### ISSUE TITLE
`EGL_KHR_platform_gbm` (but not `EGL_MESA_platform_gbm`) client extension present on EGL 1.4

### ISSUE THREAD

**Issue by fluolite** [rust-windowing/glutin#1708]
In my project, get_platform_display_ext get failed because egl client extensions mismatch。

```
egl client extensions: 
EGL_EXT_client_extensions EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_platform_gbm EGL_KHR_platform_wayland EGL_EXT_platform_wayland
```

![Screenshot_select-area_20241010115958](https://github.com/user-attachments/assets/89314cf6-5657-46c7-84af-8efc4e0ca457)

**Comment by MarijnS95** [comment]
@fluolite can you clarify what the issue is? You provided a list of extensions including `EGL_KHR_platform_gbm` and a screenshot showing that that's part of the match, but didn't detail what is meant by `In my project, get_platform_display_ext get failed`.

Specifically, can you clarify if you actually have a `RawDisplayHandle::Gbm(..)` variant? How are you calling into `glutin`, and what's the result?

**Comment by tronical** [comment]
@fluolite is using Slint IIRC and there we do create a `RawDisplayHandle::Gbm` and eventually call `glutin::display::Display::new(display_handle.as_raw(), glutin::display::DisplayApiPreference::Egl`).

**Comment by fluolite** [comment]
> Hmm, this is in `get_platform_display_ext`, but before that function is called, `get_platform_display` should've matched:
> 
> ```rust
>             RawDisplayHandle::Gbm(handle) if extensions.contains("EGL_KHR_platform_gbm") => {
>                 (egl::PLATFORM_GBM_KHR, handle.gbm_device.as_ptr())
>             },
> ```
> 
> Differently put: `EGL_KHR_platform_gbm` should patch to `(egl::PLATFORM_GBM_KHR, handle.gbm_device.as_ptr())` and not `(egl::PLATFORM_GBM_MESA, handle.gbm_device.as_ptr())`.
> 
> Could you try to see why that didn't work?


The get_platform_display did not matched!
I guess is some platform implementation did not abide by EGL extensions.
And I review qt source code, it look like always use eglGetProcAddress("eglGetPlatformDisplayEXT") 

![Screenshot_select-area_20241010180015](https://github.com/user-attachments/assets/50bdd89c-b1dc-4112-b0e8-5ab9b9f2df1e)
![Screenshot_select-area_20241010180145](https://github.com/user-attachments/assets/0f6ac2f1-1a0e-4bc9-83ec-ff1d57415155)

**Comment by fluolite** [comment]
> @fluolite can you clarify what the issue is? You provided a list of extensions including `EGL_KHR_platform_gbm` and a screenshot showing that that's part of the match, but didn't detail what is meant by `In my project, get_platform_display_ext get failed`.
> 
> Specifically, can you clarify if you actually have a `RawDisplayHandle::Gbm(..)` variant? How are you calling into `glutin`, and what's the result?

I didn't use it directly but use slint ui, and slint backend is linuxkms-skia-opengl.
The following is EGL extensions from glutin get_platform_display_ext println!.
![Screenshot_select-area_20241010180015](https://github.com/user-attachments/assets/23ed7245-4836-4125-8a30-79e3322b4a86)
![Screenshot_select-area_20241010180145](https://github.com/user-attachments/assets/b6474089-9d24-43d1-8577-1b37b6088b75)

**Comment by MarijnS95** [comment]
Thanks @tronical, I see no way how I should have that from @fluolite's minimal information.

---

@fluolite please share snippets of code in backticks instead of screenshots, they are unnecessarily hard to read and digest.

Please debug-print the value of `display; RawDisplayHandle`. I want to confirm if you truly have a `Gbm` handle and not something else.

**Comment by fluolite** [comment]
This is the debug output.

```
[root@TW02:/userdata/alien/bin]# export SLINT_BACKEND=linuxkms-skia-opengl
[root@TW02:/userdata/alien/bin]# ./slintprimer 
============================I am fix
=====================Display new
=====================get_platform_display
=====================get_platform_display is not supported
=====================get_platform_display_ext
=====================get_platform_display_ext, extensions: {"EGL_EXT_platform_wayland", "EGL_EXT_client_extensions", "EGL_EXT_platform_base", "EGL_KHR_platform_gbm", "EGL_KHR_platform_wayland", "EGL_KHR_client_get_all_proc_addresses"}
=====================get_display
Error: Other("Error creating glutin display for native display Gbm(\n    GbmDisplayHandle {\n        gbm_device: 0x000000557db98990,\n    },\n): failed to create EGLDisplay without a reason")

```

**Comment by MarijnS95** [comment]
Thanks! In your `initialize_display` logs, can you debug-print the `version` that is returned by `egl.Initialize()`?

https://github.com/rust-windowing/glutin/blob/d8e7569b1493b91d50af68156ec6cee34816fcb9/glutin/src/api/egl/display.rs#L506-L513

**Comment by fluolite** [comment]
> Thanks! In your `initialize_display` logs, can you debug-print the `version` that is returned by `egl.Initialize()`?
> 
> https://github.com/rust-windowing/glutin/blob/d8e7569b1493b91d50af68156ec6cee34816fcb9/glutin/src/api/egl/display.rs#L506-L513
> 
> Is scenario 2 working for you? I'm curious if `eglGetPlatformDisplayExt()` is allowed to work if `EGL_KHR_platform_gbm` is available, which inidcates EGL 1.5 and support/requirement for `eglGetPlatformDisplay()`.


1. The logs
```
[root@TW02:/userdata/alien/bin]# ./slintprimer 
============================I am fix
=====================Display new
=====================get_platform_display
=====================get_platform_display is not supported
=====================get_platform_display_ext
=====================get_platform_display_ext, extensions: {"EGL_KHR_platform_wayland", "EGL_EXT_platform_base", "EGL_EXT_platform_wayland", "EGL_EXT_client_extensions", "EGL_KHR_client_get_all_proc_addresses", "EGL_KHR_platform_gbm"}
=====================initialize_display
=====================initialize_display success, version major: 1, minor: 4
Using FemtoVG OpenGL renderer
Rendering at 1920x1080
Slint: Build config: debug; Backend: FemtoVG renderer
```

2. Scenario 2 working well for me,  I don't know why. I'll follow it when I can

3. EGL include headers
[Uploading EGL.zip…]()

**Comment by MarijnS95** [comment]
So that's a broken EGL driver, if it advertises EGL 1.4 but also `EGL_KHR_platform_gbm` which requires 1.5. You should probably report this to the respective driver vendor.

**Comment by MarijnS95** [comment]
I'm trying to come up with a title that is more descriptive about the actual issue at hand, since `get_platform_display_ext failed` is counter [what you said](https://github.com/rust-windowing/glutin/issues/1708#issuecomment-2407222612) that `get_platform_display_ext` actually works (because `get_platform_display` cannot be loaded) when we allow it to handle `EGL_KHR_platform_gbm`, even though the client driver should've exposed `EGL_MESA_platform_gbm`. (and/or switched to EGL 1.5 which is a requirement for `EGL_KHR_platform_gbm`, but that's a much bigger change to make)

**Comment by kchibisov** [comment]
>And as detailed above, while the value of egl::PLATFORM_GBM_KHR is equal to that of egl::PLATFORM_GBM_MESA, the extensions technically only specify that its values are valid for eglGetPlatformDisplay() and eglGetPlatformDisplayEXT() respectively so they are theoretically allowed to reject it because the combination of platform extension and function is not "allowed"?

Given that they are all the same and that EGLDisplay is the same no matter which path you take, it'll probably be fine to workaround here.

And yes, `KHR` without `eglGetPlatformDisplay` doesn't make any sense at all...

@fluolite I'd assume that

```diff
diff --git a/glutin/src/api/egl/display.rs b/glutin/src/api/egl/display.rs
index 4c2454d..ffe7cb0 100644
--- a/glutin/src/api/egl/display.rs
+++ b/glutin/src/api/egl/display.rs
@@ -362,7 +362,10 @@ impl Display {
                     handle.connection.map_or(egl::DEFAULT_DISPLAY as *mut _, |c| c.as_ptr()),
                 )
             },
-            RawDisplayHandle::Gbm(handle) if extensions.contains("EGL_MESA_platform_gbm") => {
+            RawDisplayHandle::Gbm(handle)
+                if extensions.contains("EGL_MESA_platform_gbm")
+                    || extensions.contains("EGL_KHR_platform_gbm") =>
+            {
                 (egl::PLATFORM_GBM_MESA, handle.gbm_device.as_ptr())
             },
             RawDisplayHandle::Drm(_) => {

```

works?

**Comment by kchibisov** [comment]
I generally don't mind working around stuff like that, since usually nothing can be done in some cases other than that, and it's not like we can _fail_ here, since if `KHR` worked, we'd used it, and if e.g. mesa not present but khr present, using khr will be fine, since it's the same constant.

Though, a link with justification for stuff like that would be nice.

**Comment by tronical** [comment]
> Maybe if you link the Qt source code (which would anyway be useful when referencing something...) that does this, we could reverse-search whether that followed up with an upstream report and justification of this workaround.

These are the two places I was looking at earlier:

https://github.com/qt/qtbase/blob/b429da48bed8cfa58f361ae85503c412919c3dd6/src/plugins/platforms/eglfs/deviceintegration/eglfs_kms/qeglfskmsgbmintegration.cpp#L41
https://github.com/qt/qtbase/blob/b429da48bed8cfa58f361ae85503c412919c3dd6/src/plugins/platforms/eglfs/deviceintegration/eglfs_kms/qeglfskmsgbmwindow.cpp#L28

**Comment by kchibisov** [comment]
Hm, just to make it clear, does creating surface actually work with EXT function here? Or you'd need a KHR as well for it, if that's the case it could be a bit more _weird_?

**Comment by MarijnS95** [comment]
@kchibisov it seems _yes_, per the [answer to my question 2 here](https://github.com/rust-windowing/glutin/issues/1708#issuecomment-2407222612).

(After all the enum value is the same, and the underlying function implementation likely behaves the same, even it the combination of extension version and "inferred EGL client version" is wrong)
