### ISSUE TITLE
How do I create Headless/Surfaceless contexts?

### ISSUE THREAD

**Issue by bschwind** [rust-windowing/glutin#1709]
Hi, I use this crate on Linux and MacOS but haven't updated in quite awhile. In previous versions, creating a headless context was fairly straightforward in a cross-platform way:

```rust
pub fn create_headless_shared_context<T>(
    &self,
    event_loop: &EventLoop<T>,
    size: Size,
) -> NotCurrentHeadlessGlContext {
    let context_builder = glutin::ContextBuilder::new();
    let size = size.to_physical_size();

    let context = context_builder
        .with_shared_lists(&self.context)
        .build_headless(event_loop, size)
        .unwrap();

    NotCurrentHeadlessGlContext { context }
}
```

I might just be missing something obvious, but I can no longer tell how to create the equivalent since version `0.30`. Also, do "headless" and "surfaceless" even mean the same thing?

Context: I have multiple threads doing image processing work in OpenGL, and one thread displaying the results in a window. All the "worker" threads can be headless as they shouldn't be opening windows, but they share textures so the `.with_shared_lists()` call is necessary.

I know the macos code for headless/surfaceless was probably discarded in the move to `0.30`, but if I know what the API looks like on the linux side I can probably recreate it for macos. I don't even know how to create a headless context on linux anymore with the new API, so I'd appreciate any tips on how this is typically done now.

**Comment by kchibisov** [comment]
headless context as a concept doesn't exist, it was a made up thing in old glutin.

Context doesn't need any surface to be created, the only issue is when you make it _current_ on the calling thread, and here you'd need some type of surface. The need for surface only comes once you make the context _current_ on the calling thread.

For now, only EGL can do so, if you know the way on other platforms, send a patch.

https://docs.rs/glutin/latest/glutin/api/egl/context/struct.NotCurrentContext.html#method.make_current_surfaceless

**Comment by kchibisov** [comment]
The alternative way is maybe having some sort of hidden window and activate with it on your other threads, but that's the only thing I can think of when platform doesn't support it or e.g. pbuffer/pixmap.

**Comment by bschwind** [comment]
I see, thanks! Yes I got stuck on making the context current as it required one of `PixmapSurface` (not related to macos), `PbufferSurface` (seems unsupported at the moment but _maybe_ works on macos), and `WindowSurface` (which is obviously what I'm trying to avoid).

Given that only `EGL` supports it, I suppose we don't want to add `make_current_surfaceless()` on the `NotCurrentGlContext` trait, but rather expose it directly as a platform-specific implementation?

> The alternative way is maybe having some sort of hidden window and activate with it on your other threads, but that's the only thing I can think of when platform doesn't support it or e.g. pbuffer/pixmap.

I'm pretty confident the previous implementation didn't do this, at least on macos, so I'll try adding a `make_current_surfaceless` for the `Cgl` backend first and see where that goes.

**Comment by kchibisov** [comment]
We can promote method on top-level structure once every platform has a way to do it, but for now it's like that.

Things like `make_current_surfaceless` can not be on a trait since you generally expect stuff like that to work on all platforms, otherwise your app will likely not work.
