### ISSUE TITLE
Mouse cursor grabbing

### ISSUE THREAD

**Issue by aepsil0n** [rust-windowing/glutin#226]
I just started experimenting with mouse cursor grabbing in Glutin (X11 only so far). I would like to implement this feature (eventually for FPS-like camera controls), but I am unsure about how low-level/high-level it should be.

There are essentially two components:
- Grabbing the input events from the cursor and confining its motion to the current window. (This is fairly straightforward.)
- Resetting the cursor's position to the center of the window, whenever it moves.

Now, one could either fully integrate the above functionality into Glutin and maybe generate some events about the relative mouse motion, since the absolute position is not useful any more. (This is what Piston does, apparently.)

It is also possible to only expose the low-level functionality (setting the cursor position, input grabbing) in the API and leave it up to user code to implement this.

Oh, and one should also think about how that integrates with Glium, since 3D graphics is the most common application of this.
# Implementation

Mouse grabbing:
- [x] X11: #227 
- [x] Win32: [Mouse Capture](http://winapi.freetechsecrets.com/win32/WIN32Mouse_Capture00000409.htm)
- [ ] OS/X

Set mouse cursor position:
- …

**Comment by tomaka** [comment]
I'm in favor of providing `set_mouse_position` and letting the user write `set_mouse_position(window.get_position() + window.get_outer_size() / 2)`. Glutin is low-level and shouldn't be aware of concepts like "FPS camera".

> Oh, and one should also think about how that integrates with Glium, since 3D graphics is the most common application of this.

I don't want glium to influence the design choices of glutin. Glium should adapt to glutin, not the contrary.

**Comment by XMPPwocky** [comment]
I *urgently* need some way to either get raw mouse deltas (there's an API for this on Windows) or, failing that, control the cursor (and hide it).

**Comment by fkaa** [comment]
Mouse grabbing on OSX seems to require Core Graphics via [`CGAssociateMouseAndMouseCursorPosition`](https://developer.apple.com/library/mac/documentation/GraphicsImaging/Reference/Quartz_Services_Ref/#//apple_ref/c/func/CGAssociateMouseAndMouseCursorPosition) (used by both [SDL2 ](https://hg.libsdl.org/SDL/file/4bab88dd387e/src/video/cocoa/SDL_cocoamouse.m#l237) and [GLFW](https://github.com/glfw/glfw/blob/master/src/cocoa_window.m#L1176)) but [rust-core-graphics](https://github.com/servo/rust-core-graphics/blob/master/src/display.rs) doesn't seem to implement it yet.

**Comment by griffi-gh** [comment]
> I _urgently_ need some way to either get raw mouse deltas (there's an API for this on Windows) or, failing that, control the cursor (and hide it).

Sorry for necroposting but if anyone else is trying to do it you need to use device events instead of window events!
like this:
```
    *control_flow = ControlFlow::Poll;
        match event {
            // ...
            // NEW!
            Event::DeviceEvent {
                event: DeviceEvent::MouseMotion{ delta, },
                .. // We're not using device_id currently
            } => if state.mouse_pressed {
                state.camera_controller.process_mouse(delta.0, delta.1)
            }
            ```
