### ISSUE TITLE
Add a way to recreate a context with the same window

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/glutin#501]
In case of context loss.

**Comment by tiby312** [comment]
This is the problem I am experiencing on android. If you minimize your app, and then come back to it, android may have destroyed the context. It is not guaranteed to have remained.

**Comment by ZeGentzy** [comment]
Afaik, this is achievable via the raw context extensions (even though it is not the most ergonomic thing). Sadly, this extension is only implemented for Windows and Linux. Feel free to contribute implementations of this extension for other platforms.

**Comment by kchibisov** [comment]
Fixed in #1439.
