### ISSUE TITLE
Headless context falls back to GL ES on AMD

### ISSUE THREAD

**Issue by msiglreith** [rust-windowing/glutin#583]
Creating a Headless context on windows is done via EGL. Per default `GlRequest::Latest` is set as context attribute. On my system (HD 5770 with latest drivers) the `eglBindAPI( EGL_OPENGL_API)` fails, which looks like a driver bug as the EGL 1.4 is supported. Instead of creating a OpenGL 4.5 context via WGL, the EGL implementations falls back to an OpenGL ES 3.1 context.

For example the gpgpu example of glium doesn't work due to this issue.

**Comment by kchibisov** [comment]
The headless context like it was before was removed.
