### ISSUE TITLE
Creating static bindings to EGL functions that don't exist on Android

### ISSUE THREAD

**Issue by larsbergstrom** [rust-windowing/glutin#634]
As far as I can tell, the Android EGL generation is creating bindings to a bunch of EGL 1.5 functions that are not available in any version of libEGL.so that I've been able to find (as far as I can see, it only supports up to EGL 1.4).

This is sometimes OK, if nobody calls them and you get lucky with the linker discarding them entirely. If not, though, since the Android loader does not delayload, you will fail at load.

Some examples of those symbols:

```
    00000000      D  *UND*  00000000 eglClientWaitSync
    00000000      D  *UND*  00000000 eglCreatePlatformPixmapSurface
    00000000      D  *UND*  00000000 eglCreatePlatformPixmapSurfaceEXT
    00000000      D  *UND*  00000000 eglCreatePlatformWindowSurface
    00000000      D  *UND*  00000000 eglCreatePlatformWindowSurfaceEXT
    00000000      D  *UND*  00000000 eglCreateSync
    00000000      D  *UND*  00000000 eglDestroySync
    00000000      D  *UND*  00000000 eglGetPlatformDisplay
    00000000      D  *UND*  00000000 eglGetPlatformDisplayEXT
    00000000      D  *UND*  00000000 eglGetSyncAttrib
    00000000      D  *UND*  00000000 eglWaitSync 
```

I can think of two options:
1) Switch over to dynamic loading via `eglGetProcAddress`
2) Switch the generation to only use 1.4 (and remove a bunch of the additional flags in the `vec!` that aren't supported, either) and fork the code in src/api/egl/ to support both variants.

@tomaka opinions?

**Comment by tomaka** [comment]
Option 1 is the best, but I don't know if it's technically possible. To load EGL's symbols you have to use `dlopen` or something similar. `eglGetProcAddress` only returns the addresses of the OpenGL functions as far as I know.

Option 2 would be very easy to implement right now. The code in src/api/egl already handles Android separately because of these missing symbols.
