### ISSUE TITLE
Cannot set OpenGL Profile on Windows

### ISSUE THREAD

**Issue by matklad** [rust-windowing/glutin#637]
If I build context with

``` rust
    let display = glutin::WindowBuilder::new()
        .with_dimensions(800, 800)
        .with_gl_profile(glutin::GlProfile::Core)
        .build_glium().unwrap();
```

or `.with_gl_profile(glutin::GlProfile::Compatibility)`, I get the error `BackendCreationError(NotSupported)`.

If I don't specify `gl_profile`, everything works fine. On linux all works with either profile. 

OpenGL version is `Version(Gl, 3, 3)`.

**Comment by dotfelixb** [comment]
@matklad I can't produce the same error on my system with_gl_profile(glutin::GlProfile::Compatibility) or with_gl_profile(glutin::GlProfile::Core), so if you can try cargo clean and cargo build

**Comment by matklad** [comment]
@dotfelixb I still reproduce it reliably after cargo cleain.

Here is the precise code I'm using:


```rust
extern crate glium;

use glium::{glutin, DisplayBuild};
use glium::Surface;

fn main() {
    let display = glutin::WindowBuilder::new()
        .with_dimensions(800, 800)
        // .with_gl_profile(glutin::GlProfile::Compatibility)
        // .with_gl_profile(glutin::GlProfile::Core)
        .build_glium().unwrap();

    loop {
    // listing the events produced by the window and waiting to be received
        for ev in display.poll_events() {
            match ev {
                glium::glutin::Event::Closed => return,   // the window has been closed by the user
                _ => ()
            }
            let mut target = display.draw();
            target.clear_color(0.0, 0.0, 1.0, 1.0);
            target.finish().unwrap();
        }
    }
}
```

My Cargo.toml

```rust
[package]
name = "mandelbrot"
version = "0.1.0"
authors = ["Aleksey Kladov]
license = "MIT"

[dependencies.glium]
version = "*"
features = ["glutin"]
default-features = false
```

**Comment by dotfelixb** [comment]
@matklad I still can produce the error check this tool and run the demo's and let's know the out come http://www.geeks3d.com/20150821/gpu-caps-viewer-1-25-0-gpu-information-utility-opengl-opencl-cuda/

**Comment by tomaka** [comment]
@dotfelixb When it comes to OpenGL drivers it's not particularly weird that a problem can't be reproduced.

**Comment by tomaka** [comment]
https://github.com/tomaka/glutin/blob/dcd5c49b7f479c10004c54623c73cdb4434498a8/src/api/wgl/mod.rs#L276

The problem apparently comes from the fact that your system doesn't have the `WGL_ARB_create_context_profile` extension.

This should be handled by returning an error only if compatibility is requested for a 3.2+ context, and doing nothing in other situations.

**Comment by matklad** [comment]
@dotfelixb demoes work fine. Here is a CAPS output. 

![caps](https://cloud.githubusercontent.com/assets/1711539/10451032/7030707c-71a6-11e5-91b8-efe38f1d60aa.png)

P.S. I have two GPUs, the problem is present only with intel's

**Comment by matklad** [comment]
Hm, looks like I have a really old Intel driver... After upgrading driver I was able to `.with_gl_version`, but now I have 
```
Debug message with high or medium severity: `GL error GL_INVALID_OPERATION`.
Please report this error: https://github.com/tomaka/glium/issues
```

:)

I'm reporting this to glium.

**Comment by derezzedex** [comment]
I don't understand much about this, but I cloned the repository and tested by making the if condition pass, and it worked fine.
> I think this should be changed to return an error only if compatibility is requested for a 3.2+ context, and doing nothing in other situations.

I think it has something to do [with](https://www.khronos.org/registry/OpenGL/extensions/ARB/WGL_ARB_create_context.txt):
> If the requested OpenGL version is less than 3.2,
    WGL_CONTEXT_PROFILE_MASK_ARB is ignored and the functionality of the
    context is determined solely by the requested version.

I would try to do something, but I don't how you would check the OGL version if `GlRequest::Latest` is being used.

Could you help me @tomaka ?

**Comment by derezzedex** [comment]
@tomaka or anyone?
