### ISSUE TITLE
Provide a vsync source

### ISSUE THREAD

**Issue by Yoric** [rust-windowing/glutin#640]
Servo has [an issue](https://github.com/servo/servo/issues/7782) by which it attempts to repaint (and animate, etc.) 1500 times per second. For the moment, Glutin can behave as a vsync throttler by blocking until vsync, but discussing with Gecko gfx engineers, we concluded that the best way to solve this is to provide a vsync source, and use it to trigger repaints at a reasonable framerate, [as was recently added in Gecko](https://dxr.mozilla.org/mozilla-central/source/gfx/doc/Silk.md).

I suspect that the best way to add this vsync source would be Glutin itself.

Cc @pcwalton, @nical.

**Comment by tomaka** [comment]
What does that mean in practice? As far as I know only swapping buffers with OpenGL blocks until a vsync.

**Comment by Yoric** [comment]
This means sending a signal when the hardware sends a vsync signal.

**Comment by tomaka** [comment]
I guess by "signal" you mean an event.

I can't find anything broadly related to that on the web.

**Comment by Yoric** [comment]
In the document I quoted above, I see that the hardware event can be watched using `CVDisplayLinkRef` on MacOS X, `DwmGetCompositionTimingInfo` on Windows, `HwcComposer2D` on Android. I don't see anything about other platforms.

**Comment by Yoric** [comment]
What's your judgement, @tomaka? Should this be part of Glutin, or an independent crate/lib?

**Comment by tomaka** [comment]
Looking at `DwmGetCompositionTimingInfo`, a function to query the refresh rate of the window should be part of glutin but the system that sends events is out of scope of glutin.

**Comment by kchibisov** [comment]
See https://github.com/rust-windowing/winit/issues/2412.
