### ISSUE TITLE
Redesign window building API with abstract video modes

### ISSUE THREAD

**Issue by sleeparrow** [rust-windowing/glutin#648]
I propose we change the way windows are built such that all windows (fullscreen or not) will require an abstract `VideoMode` argument.

A `VideoMode` will represent either the dimensions of a non-fullscreen window, or an actual fullscreen mode. Non-fullscreen `VideoMode`s will be instantiable with custom dimensions, while fullscreen `VideoMode` will be opaque.

To get a fullscreen `VideoMode`, you must select one from a list returned from another public function; let's call it `get_fullscreen_modes()`. You can examine the values (width/height/`PixelFormat`) of this `VideoMode`, but you cannot change them. This may prove a better alternative to the current behavior, which just looks at the argument given to `with_dimensions` (or a default) and searches for a larger video mode.

Here's what the structures in question might look like:

``` rust
enum VideoMode {
    Windowed(u32, u32),
    Fullscreen(FullscreenMode),
}

// maybe dependent on platform; notice the opacity
struct FullscreenMode {
    width: u32,
    height: u32,
    // internal ID of the mode, etc.
}
```

This design is based on SFML's [`sf::VideoMode`](http://www.sfml-dev.org/documentation/2.2/classsf_1_1VideoMode.php) class.

**Comment by vberger** [comment]
Just to give the wayland point of view on this.

Wayland does not give direct access to the video modes, but rather lets the compositor (aka graphic server) handle the down/up-scaling if necessary. The client only provides a hint about *how* it should be done, via an enum (see [FullscreenMethod](http://vberger.github.io/wayland-client-rs/wayland_client/wayland/shell/enum.WlShellSurfaceFullscreenMethod.html)).

How would this fit into this design proposal ?

**Comment by adambadawy** [comment]
Well, `get_fullscreen_modes()` could return the Wayland hints! As to how we would make this clear in the API, not sure yet.

**Comment by Havvy** [comment]
`Windowed` is a better name than `NotFullScreen`.

**Comment by tomaka** [comment]
I'd prefer if `VideoMode` was fullscreen-only.

**Comment by adambadawy** [comment]
@tomaka The name is misleading, but the advantage of putting this data in one place is that users know they're making an explicit choice between dimensions and fullscreen modes. Maybe a different name would be better?

**Comment by tomaka** [comment]
What I mean is that if we take your example, I'd rename `FullscreenMode` to `VideoMode` and `VideoMode` to something more trivial like `WindowConfig`.

**Comment by adambadawy** [comment]
That sounds good to me.

**Comment by tomaka** [comment]
The `Windowed` variant of the `WindowConfig` would contain things like `decorations` or `title` which aren't relevant for fullscreen.

**Comment by adambadawy** [comment]
I don't know how much of an exception Wayland is with regard to their protocol, but what if fullscreen mode were an enum like this:

```rust
enum FullscreenMode {
    SizedMode(SizedMode),
    BehaviorHintMode(BehaviorHintMode),
}

struct SizedMode {
    // Opaque. Defines methods to inspect the dimensions.
}

struct BehaviorHintMode {
    // Opaque. Defines `get_hint(&self) -> &BehaviorHint`.
}

enum BehaviorHint {
    Default, Scale, Driver, Fill
    // if other platforms have a behavioral hint style, we can put them here, too; they won't be 
    // returned if we're not on Wayland
}
```

**Comment by adambadawy** [comment]
And then we take the path of least surprise for `get_fullscreen_modes()[0]` so nobody has to worry about this. :sunglasses:

**Comment by vberger** [comment]
Well, actually I don't think it'll require such a separation. Wayland still allows you to define a size for the window, there are just no requirement for it to fit one of the display's video mode (but you can still do it, so that no scaling is needed).

No need to overthink it. I would say, first reach something that is satisfactory for the platforms currently supported by glutin (wayland isn't yet one of them !), I'll let you know if anything is problematic for me. :wink:

**Comment by adambadawy** [comment]
Another thought on this: we could have another public function `request_fullscreen_mode(...)`. This would fit better with Wayland's more relaxed fullscreen mode constraints.

I also just realized you can probably create an X11 `XF86VidModeModeInfo` object yourself and check it with `XF86VidModeValidateModeLine`, so this should be a useful function on platforms other than Wayland.

We could even pass a function `Fn(FullscreenMode) -> bool` as an argument to `request_fullscreen_mode` for maximum flexibility.

**Comment by adambadawy** [comment]
To clarify, we'd pass specific constraints to `request_fullscreen_mode`. Maybe with some kind of `FullscreenModeConstraints` struct with a bunch of `Option`s, so we could optionally compare a bunch of values. We might need to do some funky stuff like allow any Wayland mode pass through size constraints.

**Comment by genodeftest** [comment]
I think relying on `XFree86-VidModeExtension` is a bad idea. It fails on XWayland (an rootless X server nested in a wayland session). 
```
$ ./mach run tests/html/about-mozilla.html
Xlib:  extension "XFree86-VidModeExtension" missing on display ":0".
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: OsError("Could not query the video modes")', ../src/libcore/result.rs:741
stack backtrace:
   1:     0x557ac28e5c10 - sys::backtrace::tracing::imp::write::h064b2475ee0d772cxXt
   2:     0x557ac28e8b55 - panicking::log_panic::_<closure>::closure.40992
   3:     0x557ac28e85d0 - panicking::log_panic::h29f8d24759545d7862x
   4:     0x557ac28d1213 - sys_common::unwind::begin_unwind_inner::hdadcc96a1ecb24974Ps
   5:     0x557ac28d18c8 - sys_common::unwind::begin_unwind_fmt::h9442bd88fc02b35caPs
   6:     0x557ac28e5271 - rust_begin_unwind
   7:     0x557ac2915d0f - panicking::panic_fmt::h2f3428e3725b99d6VFK
   8:     0x557ac163021c - window::_<impl>::new::h57934a50b43f4bf7Bxa
   9:     0x557ac162f6dd - create_window::hacaa88232813d2e8U8a
  10:     0x557ac0d15a48 - main::hb77cfbfb032d8741Laa
  11:     0x557ac28e8374 - sys_common::unwind::try::try_fn::h8142129006887684815
  12:     0x557ac28e50b8 - __rust_try
  13:     0x557ac28e8016 - rt::lang_start::h47c94448bf012481e0x
  14:     0x7f726091457f - __libc_start_main
  15:     0x557ac0d096c8 - _start
  16:                0x0 - <unknown>
Servo exited with return value 101
```

**Comment by AaronFriel** [comment]
👍 to @genodeftest 

This is also a blocking issue for using Glutin with remote X, and is an issue if you want to say, run an X server on your host OS and run an application in a virtual machine or using something like Windows Services for Linux.

**Comment by vberger** [comment]
To give some heads up regarding wayland, my previous comments are outdated. Givent the new getting-standard protocol (xdg_shell), the client cannot request anything more precise than "fullscreen". The server alone chooses how it does it.

In practice, I think this means on wayland the inly thing available is what I believe Windows calls "windowed fullscreen".

**Comment by kchibisov** [comment]
No winit in glutin anymore.
