### ISSUE TITLE
Support listing available video modes for a monitor

### ISSUE THREAD

**Issue by mikeroll** [rust-windowing/glutin#742]
The only videomode-related stuff I found is [MonitorId::get_dimensions](http://tomaka.github.io/glutin/glutin/struct.MonitorId.html#method.get_dimensions)
It would be nice to have access to all available modes for a monitor ([like this](http://bvssvni.github.io/docs/glfw-rs/glfw/struct.Monitor.html#method.get_video_modes))
And as I side effect all video mode info could be incapsulated into in a struct ([like this](http://bvssvni.github.io/docs/glfw-rs/glfw/struct.VidMode.html))

**Comment by ZeGentzy** [comment]
https://github.com/rust-windowing/winit/issues/877
