### ISSUE TITLE
Implement swap interval for android

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/glutin#81]

**Comment by dvc94ch** [comment]
@tomaka can you elaborate on what you mean with this? is it related to https://github.com/rust-windowing/winit/pull/1328/commits/2a397301336acad8d19a77ce574e2b7c87dafba6?

**Comment by goddessfreya** [comment]
@dvc94ch 

Back in October 2014, vsync on Android was not a thing, see: https://github.com/rust-windowing/glutin/blob/118b7d32b4edc7c961f93e1c841d6aca04dee550/src/android/mod.rs
It was possible to set the swap interval to 1 on windows, see: https://github.com/rust-windowing/glutin/blob/118b7d32b4edc7c961f93e1c841d6aca04dee550/src/win32/init.rs#L350 .

#1271 expands the api to allow setting the swap interval to values other than 1.
