### ISSUE TITLE
Detect errors on calls to *MakeCurrent

### ISSUE THREAD

**Issue by tomaka** [rust-windowing/glutin#84]
For the moment, calls to `wglMakeCurrent`, `glXMakeCurrent`, etc. can silently fail.
The return type of `make_current` should be a `Result<(), MakeCurrentError>`.

**Comment by ZeGentzy** [comment]
Has already been fixed.

**Comment by ZeGentzy** [comment]
Nvm, damn macos & emscripten

**Comment by kchibisov** [comment]
I'll close this, given that there's no evidence of error handling on macOS for context stuff.
