### ISSUE TITLE
Better OpenGL ES support

### ISSUE THREAD

**Issue by torkleyy** [rust-windowing/glutin#861]
My phone: LG P880 (4x hd)

I can't use glutin on my phone because [this line](https://github.com/tomaka/glutin/blob/master/src/api/egl/mod.rs#L497) causes the application to panic.

I'm not sure if this is the reason but it has some sort of nvidia Tegra chip.

Is it possible to handle that case or why was it left out?

**Comment by torkleyy** [comment]
@tomaka The bug is in [line 214](https://github.com/tomaka/glutin/blob/master/src/api/egl/mod.rs#L214) because my `egl_version` is (1, 4).

**Comment by tomaka** [comment]
The bug is the fact that it's unimplemented, not the fact that `version` contains `None`.

The `unimplemented!` is supposed to be the code that automatically detects which version of OpenGL ES is supported.

**Comment by torkleyy** [comment]
@tomaka I see, ok. However, I tried to work around that problem by specifying a version, and I got another panic because [this line](NoAvailablePixelFormat) caused a `NoAvailablePixelFormat` error (it seems the requested configuration is not supported).

**Comment by torkleyy** [comment]
Is there any documentation for `eglGetConfigs`?

**Comment by torkleyy** [comment]
@tomaka Same error with `Nexus 5X`. I'd really like to fix this, but I don't know how to implement it.

**Comment by kchibisov** [comment]
Fixed in #1439.
