### ISSUE TITLE
Setting robustness with EGL fails

### ISSUE THREAD

**Issue by vberger** [rust-windowing/glutin#892]
Steps to reproduce:

- Modify the example `window.rs` by adding `.with_gl_robustness(Robustness::TryRobustLoseContextOnReset)` to the window builder
- Run the example under wayland **or** under X11 while forcing the use of EGL (by modifying `platform::linux::x11::GlxOrEgl` to ignore GLX for example)

The window building returns `Err(OpenGlVersionNotSupported)`, because `egl.CreateContext` generated a `BAD_ATTRIBUTE` EGL error.

This has been reproduced one 3 computers, 2 using mesa and 1 using the nvidia proprietary drivers.

**Comment by kchibisov** [comment]
Fixed in #1439. If not reopen.
