### ISSUE TITLE
Context sharing not implemented for many platforms

### ISSUE THREAD

**Issue by mitchmindtree** [rust-windowing/glutin#899]
This is a tracking issue for the state of context display list sharing for each backend. 

- [x] Linux | Wayland | EGL
- [x] Linux | X11 | EGL
- [x] Linux | X11 | GLX
- [x] Windows | WGL
- [x] Windows | EGL
- [x] macOS
- [ ] iOS
- [ ] Android

**Comment by ZeGentzy** [comment]
Linux support + windows w/ egl has been added in #1101.

**Comment by kchibisov** [comment]
Fixed in #1439.
