### ISSUE TITLE
Dealing with Android Activity Lifecycle

### ISSUE THREAD

**Issue by torkleyy** [rust-windowing/glutin#904]
What is the recommended way to handle a paused activity?

The problem is that it is not allowed to swap buffers then, so I suppose the application should just wait until it is resumed.

**Comment by tiby312** [comment]
Yes I would like to know as well. When I minimize the app and re open it, I just have a blank screen. Does the display need to be rebuilt based off of the Suspend Event?

**Comment by ip** [comment]
The GL context is destroyed and every GL resource has to be initialized again.

**Comment by kchibisov** [comment]
Out of scope for glutin.
