### ISSUE TITLE
10 bit color support?

### ISSUE THREAD

**Issue by rennis250** [rust-windowing/glutin#921]
Is it possible to support a 10 bit color context? This is necessary for my work, and I will be forced to use GLFW with raw OpenGL until it is available. I'm sure others would also benefit from this. For clarity, I mean that each color channel has 10-bit color resolution and this would be measurable in the luminance emitted from the monitor. To achieve this with GLFW, I do the following:

```
GLFWWindowHint(GL_RED_BITS, 10);
GLFWWindowHint(GL_GREEN_BITS, 10);
GLFWWindowHint(GL_BLUE_BITS, 10);
GLFWWindowHint(GL_ALPHA_BITS, 2);
```

Best and thanks,
Rob

**Comment by tomaka** [comment]
In the past I decided to only expose the number of color bits and alpha bits: https://docs.rs/glutin/0.9.2/glutin/struct.ContextBuilder.html#method.with_pixel_format

The problem is that I don't remember why.

**Comment by tomaka** [comment]
Ah yeah, MacOS as usual: https://github.com/tomaka/glutin/blob/9625c81c359d14458a197b571c3e566a76334084/src/platform/macos/helpers.rs#L54-L55

**Comment by rennis250** [comment]
Hmm... so you mean that if I do something like:

```
... .with_pixel_format(self, 10, 2);
```

then, there is a possibility that I could get 10-bit color or no? Regardless, I may test this on our 10-bit monitor later today. I would only be using Linux and Windows.

Best,
Rob

**Comment by tomaka** [comment]
No, it would be `.with_pixel_format(30, 2)`

**Comment by ZeGentzy** [comment]
Too outdated.
