### ISSUE TITLE
Static function linking

### ISSUE THREAD

**Issue by kvark** [rust-windowing/glutin#965]
Here is an interesting piece of http://kripken.github.io/emscripten-site/docs/optimizing/Optimizing-WebGL.html#optimizing-load-times-and-other-best-practices:
> Avoid using any of the ``*glGetProcAddress()`` API functions. Emscripten provides static linking to all of the GL API functions, even for all WebGL extensions. The ``*glGetProcAddress()`` API is only provided for compatibility to ease porting of existing code, but accessing WebGL via calling dynamically obtained function pointers is noticeably slower than direct function calls, due to extra function pointer security validation that dynamic dispatching has to do in asm.js/WebAssembly. Since Emscripten provides all of the GL entry points statically linked in, it is recommended to take advantage of this for best performance.

Is there a way to link all GL functions statically as opposed to `get_proc_address`?

**Comment by kvark** [comment]
Relevant - https://github.com/kripken/emscripten/pull/5951

**Comment by kchibisov** [comment]
We don't have emscripten for a long time iirc.
