### ISSUE TITLE
The first example uses 30% of the cpu.

### ISSUE THREAD

**Issue by ghost** [rust-windowing/glutin#974]
Why? It's just a green screen...

**Comment by DoctorVWA** [comment]
I changed the while loop for the event_loop.run_forever method showed in the window.rs example, it is working and isn't using 30% cpu

**Comment by DoctorVWA** [comment]
I still worried about the cpu use, it in idle, is using 6%, when I resize uses 12, I don't know if it's just I being a morron...

**Comment by ZeGentzy** [comment]
Eventloop v2 prolly helps this. If you are still concerned over cpu use, reopen
