### ISSUE TITLE
Transparency issue when using window visibility on X11/NVIDIA

### ISSUE THREAD

**Issue by 13k** [rust-windowing/glutin#984]
OS: `Linux 4.14.13-300.fc27.x86_64 #1 SMP Thu Jan 11 04:00:01 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux`
Distro: Fedora 27
OpenGL info: https://gist.github.com/13k/58ec3d41dfcc038aaf48862028e50e77

---

As I reported in https://github.com/jwilm/alacritty/issues/1059, alacritty is now using a [technique to spawn an invisible window then immediately showing it](https://github.com/jwilm/alacritty/blob/b82622e9948d1c90fc628739c7f328816214fb33/src/window.rs#L197-L205), to avoid [delayed window start issues](https://github.com/jwilm/alacritty/issues/875), but as you can see in a [later comment of mine](https://github.com/jwilm/alacritty/issues/1059#issuecomment-361311821), using this technique will cause, at least in my system, the transparency to behave strangely.

**Comment by 13k** [comment]
It looks like it's an issue with NVIDIA's FXAA implementation.

As I commented [here](https://github.com/alacritty/alacritty/issues/2287#issuecomment-515757169), disabling FXAA seems to fix the issue and is a viable workaround.

I tested on both Windows (per comment above) and Linux (same hardware).

**Comment by chrisduerr** [comment]
@13k Thanks a lot for following up to this after such a long time. When you say this seems to be an issue with Nvidia's FXAA implementation, that sounds like the issue lies solely within Nvidia's responsibility?

Does switching to the open source driver resolve that issue? If so, it probably doesn't make much sense to track this in Alacritty and Glutin, since we have no way to fix a bug in the Nvidia driver.

**Comment by 13k** [comment]
> Thanks a lot for following up to this after such a long time.

Sorry for taking so long, I forgot about these open issues.

I'm not a CG expert, so I apologize if I sound stupid:

From what I understood, after doing a superficial research on this (https://github.com/electron/electron/issues/13646, [fxaa tutorial](https://catlikecoding.com/unity/tutorials/advanced-rendering/fxaa/), [nvidia forum comment](https://www.nvidia.com/en-us/geforce/forums/game-ready-drivers/13/150711/fxaa-control-panel-vs-ingame/1102050/), [nvidia's fxaa sample](https://docs.nvidia.com/gameworks/content/gameworkslibrary/graphicssamples/opengl_samples/fxaa.htm)), FXAA is a post-processing filter that implements a cheap anti-aliasing technique. It can be implemented by the application itself, like some games do, and the application decides whenever/wherever it wants it applied. Nvidia's driver also provides an implementation and, when the FXAA option in the driver settings is enabled, it gets applied to whatever the application is rendering.

So what I infer from this is that the FXAA driver option is available either for a) users who want to disable the application's expensive AA and get a cheap AA from the driver; or b) applications that don't implement AA.

Also, I guess the application has no control over or knowledge about the driver's FXAA being enabled or not.

> When you say this seems to be an issue with Nvidia's FXAA implementation, that sounds like the issue lies solely within Nvidia's responsibility?
> Does switching to the open source driver resolve that issue?
> If so, it probably doesn't make much sense to track this in Alacritty and Glutin, since we have no way to fix a bug in the Nvidia driver.

With all above said and since it also happens with electron, both on Linux and Windows (same as Alacritty), I think a good guess is that it's Nvidia's responsiblity.

I don't know about the `nouveau` driver, but a quick search didn't turn up anything about it providing FXAA.

**Comment by 13k** [comment]
I'm cleaning up my open issues and this one seems like is an upstream (NVIDIA) issue. Feel free to reopen if this is a mistake.
