### ISSUE TITLE
Support statically-linked libEGL? (On Windows)

### ISSUE THREAD

**Issue by SimonSapin** [rust-windowing/glutin#997]
https://github.com/servo/mozangle compiles ANGLE, on Windows with an EGL implementation. To avoid the complication of shipping `.dll` files separately, it is linked as a static library.

Glutin supports EGL on Windows, but loads it from a dynamic library like `libEGL.dll`. What do you think of adding support for statically-linked EGL?

Conditionally having something like `extern { fn eglGetProcAddress(…) }` directly in Glutin would require a compile-time flag, which isn’t great. So maybe that function could be (optionally) provided by users:

```rust
impl<'a> ContextBuilder<'a> {
    pub fn with_egl_get_proc_address<F>(mut self, get_proc_address: F) -> Self
        where F: Fn(&str) -> *const c_void
    {
        self.egl_get_proc_address = Some(Box::new(get_proc_address))
        self
    }
}
```

Since this is only relevant on Windows, maybe it should be in a `glutin::os::windows::ContextBuilderExt` trait.

Or maybe something more automagic could be made with weak symbols, but those don’t seem to be available in Stable Rust.

Thoughts?

**Comment by jdm** [comment]
The original motivating example of https://github.com/servo/mozangle/ is no longer relevant. We have since modified the build to generate a libEGL.dll on Windows if desired.

**Comment by SimonSapin** [comment]
@jdm Does this involve a build system around Cargo copying the dll file to the right place?

**Comment by jdm** [comment]
It does, yes.
